import { chromium } from "@playwright/test";
const O = "https://alu.kairo.vn";
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 1200 } });
await page.goto(O + "/x/action%3Acat-nhom");
await page.locator("#mf-login-usr").fill("admin");
await page.locator("#mf-login-pwd").fill("admin@2026");
await page.getByRole("button", { name: "Đăng nhập" }).click();
await page.waitForTimeout(6000);
await page.goto(O + "/x/action%3Acat-nhom");
await page.waitForTimeout(5000);
await page.locator("#action-cat-nhom-profile").click();
await page.waitForTimeout(800);
await page.keyboard.type("AL548");
await page.waitForTimeout(3000);
await page.screenshot({ path: "dbg-link.png", fullPage: true });
console.log("OPTIONS:", (await page.getByRole("option").allInnerTexts()).slice(0,6).join(" | "));
console.log("BUTTONS:", (await page.getByRole("button").allInnerTexts()).map(t=>t.trim()).filter(Boolean).join(" | "));
await browser.close();
