import type { JsonObject } from "../../contracts/src/index.js";
import type { SalesItem, TaxRow } from "./types.js";

export interface QuotationData extends JsonObject {
  crm_deal?: string | undefined;
  customer?: string | undefined;
  company: string;
  currency: string;
  currency_scale?: number | undefined;
  transaction_date: string;
  valid_till: string;
  selling_price_list?: string | undefined;
  customer_group?: string | undefined;
  apply_discount_on?: "Net Total" | "Grand Total" | undefined;
  additional_discount_percentage?: string | number | undefined;
  discount_amount?: string | number | undefined;
  items: SalesItem[];
  taxes?: TaxRow[] | undefined;
  revision_no?: number | undefined;
  net_total?: string | undefined;
  net_total_minor?: number | undefined;
  total_taxes_and_charges?: string | undefined;
  total_taxes_and_charges_minor?: number | undefined;
  grand_total?: string | undefined;
  grand_total_minor?: number | undefined;
  rounded_total?: string | undefined;
  rounded_total_minor?: number | undefined;
  rounding_adjustment?: string | undefined;
  rounding_adjustment_minor?: number | undefined;
  company_currency?: string | undefined;
  company_currency_scale?: number | undefined;
  conversion_rate?: string | undefined;
  conversion_rate_micros?: number | undefined;
  base_net_total?: string | undefined;
  base_net_total_minor?: number | undefined;
  base_total_taxes_and_charges?: string | undefined;
  base_total_taxes_and_charges_minor?: number | undefined;
  base_grand_total?: string | undefined;
  base_grand_total_minor?: number | undefined;
}
