-- Frappe minimum platform: metadata, workflow, collaboration, files, print and naming.
CREATE TABLE IF NOT EXISTS doctype_definitions (
  tenant_id TEXT NOT NULL,
  doctype TEXT NOT NULL,
  module TEXT NOT NULL,
  is_custom INTEGER NOT NULL DEFAULT 0 CHECK (is_custom IN (0,1)),
  is_submittable INTEGER NOT NULL DEFAULT 0 CHECK (is_submittable IN (0,1)),
  is_child INTEGER NOT NULL DEFAULT 0 CHECK (is_child IN (0,1)),
  revision INTEGER NOT NULL CHECK (revision > 0),
  metadata_json TEXT NOT NULL CHECK (json_valid(metadata_json)),
  disabled INTEGER NOT NULL DEFAULT 0 CHECK (disabled IN (0,1)),
  modified_by TEXT NOT NULL,
  modified_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id, doctype)
);
CREATE INDEX IF NOT EXISTS idx_doctype_module ON doctype_definitions(tenant_id,module,doctype);

CREATE TABLE IF NOT EXISTS workflows (
  tenant_id TEXT NOT NULL,
  name TEXT NOT NULL,
  document_type TEXT NOT NULL,
  is_active INTEGER NOT NULL DEFAULT 1 CHECK (is_active IN (0,1)),
  revision INTEGER NOT NULL CHECK (revision > 0),
  workflow_json TEXT NOT NULL CHECK (json_valid(workflow_json)),
  modified_by TEXT NOT NULL,
  modified_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id,name)
);
CREATE UNIQUE INDEX IF NOT EXISTS idx_workflow_active_doctype ON workflows(tenant_id,document_type) WHERE is_active=1;

CREATE TABLE IF NOT EXISTS naming_series (
  tenant_id TEXT NOT NULL,
  series_key TEXT NOT NULL,
  current_value INTEGER NOT NULL DEFAULT 0 CHECK (current_value >= 0),
  modified_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id,series_key)
);

CREATE TABLE IF NOT EXISTS document_comments (
  tenant_id TEXT NOT NULL,
  comment_id TEXT NOT NULL,
  doctype TEXT NOT NULL,
  name TEXT NOT NULL,
  comment_type TEXT NOT NULL CHECK (comment_type IN ('Comment','Edit','Shared','Assigned','Info')),
  content TEXT NOT NULL,
  owner TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id,comment_id)
);
CREATE INDEX IF NOT EXISTS idx_comments_document ON document_comments(tenant_id,doctype,name,created_at);

CREATE TABLE IF NOT EXISTS assignments (
  tenant_id TEXT NOT NULL,
  assignment_id TEXT NOT NULL,
  doctype TEXT NOT NULL,
  name TEXT NOT NULL,
  assigned_to TEXT NOT NULL,
  description TEXT,
  status TEXT NOT NULL CHECK (status IN ('Open','Closed','Cancelled')),
  priority TEXT CHECK (priority IS NULL OR priority IN ('Low','Medium','High')),
  due_date TEXT,
  owner TEXT NOT NULL,
  created_at TEXT NOT NULL,
  modified_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id,assignment_id)
);
CREATE INDEX IF NOT EXISTS idx_assignments_user ON assignments(tenant_id,assigned_to,status,due_date);
CREATE INDEX IF NOT EXISTS idx_assignments_document ON assignments(tenant_id,doctype,name,status);

CREATE TABLE IF NOT EXISTS document_shares (
  tenant_id TEXT NOT NULL,
  doctype TEXT NOT NULL,
  name TEXT NOT NULL,
  user TEXT NOT NULL,
  can_read INTEGER NOT NULL DEFAULT 1 CHECK (can_read IN (0,1)),
  can_write INTEGER NOT NULL DEFAULT 0 CHECK (can_write IN (0,1)),
  can_share INTEGER NOT NULL DEFAULT 0 CHECK (can_share IN (0,1)),
  submitted_by TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id,doctype,name,user)
);
CREATE INDEX IF NOT EXISTS idx_shares_user ON document_shares(tenant_id,user,doctype);

CREATE TABLE IF NOT EXISTS files (
  tenant_id TEXT NOT NULL,
  file_id TEXT NOT NULL,
  file_name TEXT NOT NULL,
  content_type TEXT NOT NULL,
  size_bytes INTEGER NOT NULL CHECK (size_bytes >= 0),
  storage_key TEXT NOT NULL,
  attached_to_doctype TEXT,
  attached_to_name TEXT,
  is_private INTEGER NOT NULL DEFAULT 1 CHECK (is_private IN (0,1)),
  owner TEXT NOT NULL,
  created_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id,file_id),
  UNIQUE (tenant_id,storage_key)
);
CREATE INDEX IF NOT EXISTS idx_files_document ON files(tenant_id,attached_to_doctype,attached_to_name,created_at);

CREATE TABLE IF NOT EXISTS print_formats (
  tenant_id TEXT NOT NULL,
  name TEXT NOT NULL,
  doc_type TEXT NOT NULL,
  is_default INTEGER NOT NULL DEFAULT 0 CHECK (is_default IN (0,1)),
  disabled INTEGER NOT NULL DEFAULT 0 CHECK (disabled IN (0,1)),
  revision INTEGER NOT NULL CHECK (revision > 0),
  format_json TEXT NOT NULL CHECK (json_valid(format_json)),
  modified_by TEXT NOT NULL,
  modified_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id,name)
);
CREATE INDEX IF NOT EXISTS idx_print_formats_doctype ON print_formats(tenant_id,doc_type,is_default DESC,name);

CREATE TABLE IF NOT EXISTS import_jobs (
  tenant_id TEXT NOT NULL,
  job_id TEXT NOT NULL,
  doctype TEXT NOT NULL,
  actor_id TEXT NOT NULL,
  status TEXT NOT NULL CHECK (status IN ('Preview','Queued','Running','Completed','Failed','Cancelled')),
  request_json TEXT NOT NULL CHECK (json_valid(request_json)),
  result_json TEXT CHECK (result_json IS NULL OR json_valid(result_json)),
  created_at TEXT NOT NULL,
  completed_at TEXT,
  PRIMARY KEY (tenant_id,job_id)
);
CREATE INDEX IF NOT EXISTS idx_import_jobs_status ON import_jobs(tenant_id,status,created_at);

CREATE TABLE IF NOT EXISTS notification_rules (
  tenant_id TEXT NOT NULL,
  name TEXT NOT NULL,
  document_type TEXT NOT NULL,
  event TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 1 CHECK (enabled IN (0,1)),
  rule_json TEXT NOT NULL CHECK (json_valid(rule_json)),
  modified_by TEXT NOT NULL,
  modified_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id,name)
);

-- Seed a minimal standard metadata catalog for the demo tenant. Production provisioning
-- must copy these definitions into every tenant rather than relying on a shared tenant.
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Currency','Setup',0,0,0,1,'{"name":"Currency","module":"Setup","custom":false,"is_submittable":false,"track_changes":true,"fields":[{"fieldname":"currency_name","label":"Currency Name","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"symbol","label":"Symbol","fieldtype":"Data","in_list_view":true},{"fieldname":"currency_scale","label":"Precision","fieldtype":"Int","required":true,"default":2,"in_list_view":true,"in_standard_filter":true}],"permissions":[{"role":"System Manager","read":true,"write":true,"create":true,"submit":true,"cancel":true,"amend":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Accounts Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true}],"revision":1,"sort_field":"modified_at","sort_order":"DESC","title_field":"currency_name","autoname":"field:name","search_fields":["currency_name","symbol"]}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Company','Setup',0,0,0,1,'{"name":"Company","module":"Setup","custom":false,"is_submittable":false,"track_changes":true,"fields":[{"fieldname":"company_name","label":"Company Name","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"default_currency","label":"Default Currency","fieldtype":"Link","options":"Currency","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"tax_id","label":"Tax ID","fieldtype":"Data","in_list_view":true},{"fieldname":"country","label":"Country","fieldtype":"Data","in_standard_filter":true},{"fieldname":"disabled","label":"Disabled","fieldtype":"Check","default":false,"in_standard_filter":true}],"permissions":[{"role":"System Manager","read":true,"write":true,"create":true,"submit":true,"cancel":true,"amend":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Accounts Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true}],"revision":1,"sort_field":"modified_at","sort_order":"DESC","title_field":"company_name","autoname":"field:name","search_fields":["company_name","tax_id"]}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','UOM','Stock',0,0,0,1,'{"name":"UOM","module":"Stock","custom":false,"is_submittable":false,"track_changes":true,"fields":[{"fieldname":"uom_name","label":"UOM Name","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"must_be_whole_number","label":"Must Be Whole Number","fieldtype":"Check","default":false,"in_standard_filter":true}],"permissions":[{"role":"System Manager","read":true,"write":true,"create":true,"submit":true,"cancel":true,"amend":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Stock Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true}],"revision":1,"sort_field":"modified_at","sort_order":"DESC","title_field":"uom_name","autoname":"field:name","search_fields":["uom_name"]}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Customer','Selling',0,0,0,1,'{"name":"Customer","module":"Selling","custom":false,"is_submittable":false,"track_changes":true,"fields":[{"fieldname":"customer_name","label":"Customer Name","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"customer_group","label":"Customer Group","fieldtype":"Data","in_list_view":true,"in_standard_filter":true},{"fieldname":"tax_id","label":"Tax ID","fieldtype":"Data","in_list_view":true},{"fieldname":"default_currency","label":"Default Currency","fieldtype":"Link","options":"Currency","in_list_view":true},{"fieldname":"disabled","label":"Disabled","fieldtype":"Check","default":false,"in_standard_filter":true}],"permissions":[{"role":"System Manager","read":true,"write":true,"create":true,"submit":true,"cancel":true,"amend":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Sales Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Sales User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Accounts Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true}],"revision":1,"sort_field":"modified_at","sort_order":"DESC","title_field":"customer_name","autoname":"CUST-.YYYY.-#####","search_fields":["customer_name","tax_id"]}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Supplier','Buying',0,0,0,1,'{"name":"Supplier","module":"Buying","custom":false,"is_submittable":false,"track_changes":true,"fields":[{"fieldname":"supplier_name","label":"Supplier Name","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"supplier_group","label":"Supplier Group","fieldtype":"Data","in_list_view":true,"in_standard_filter":true},{"fieldname":"tax_id","label":"Tax ID","fieldtype":"Data","in_list_view":true},{"fieldname":"default_currency","label":"Default Currency","fieldtype":"Link","options":"Currency","in_list_view":true},{"fieldname":"disabled","label":"Disabled","fieldtype":"Check","default":false,"in_standard_filter":true}],"permissions":[{"role":"System Manager","read":true,"write":true,"create":true,"submit":true,"cancel":true,"amend":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Purchase Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Purchase User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Accounts Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true}],"revision":1,"sort_field":"modified_at","sort_order":"DESC","title_field":"supplier_name","autoname":"SUP-.YYYY.-#####","search_fields":["supplier_name","tax_id"]}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Item','Stock',0,0,0,1,'{"name":"Item","module":"Stock","custom":false,"is_submittable":false,"track_changes":true,"fields":[{"fieldname":"item_name","label":"Item Name","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"item_group","label":"Item Group","fieldtype":"Data","in_list_view":true,"in_standard_filter":true},{"fieldname":"stock_uom","label":"Stock UOM","fieldtype":"Link","options":"UOM","required":true,"in_list_view":true},{"fieldname":"is_stock_item","label":"Is Stock Item","fieldtype":"Check","default":true,"in_standard_filter":true},{"fieldname":"valuation_method","label":"Valuation Method","fieldtype":"Select","options":"FIFO\nMoving Average","default":"FIFO","in_list_view":true},{"fieldname":"disabled","label":"Disabled","fieldtype":"Check","default":false,"in_standard_filter":true}],"permissions":[{"role":"System Manager","read":true,"write":true,"create":true,"submit":true,"cancel":true,"amend":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Stock Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Stock User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Sales Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Purchase Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true}],"revision":1,"sort_field":"modified_at","sort_order":"DESC","title_field":"item_name","autoname":"ITEM-.YYYY.-#####","search_fields":["item_name"]}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Warehouse','Stock',0,0,0,1,'{"name":"Warehouse","module":"Stock","custom":false,"is_submittable":false,"track_changes":true,"fields":[{"fieldname":"warehouse_name","label":"Warehouse Name","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"parent_warehouse","label":"Parent Warehouse","fieldtype":"Link","options":"Warehouse"},{"fieldname":"is_group","label":"Is Group","fieldtype":"Check","default":false,"in_standard_filter":true},{"fieldname":"disabled","label":"Disabled","fieldtype":"Check","default":false,"in_standard_filter":true}],"permissions":[{"role":"System Manager","read":true,"write":true,"create":true,"submit":true,"cancel":true,"amend":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Stock Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Stock User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true}],"revision":1,"sort_field":"modified_at","sort_order":"DESC","title_field":"warehouse_name","autoname":"field:name","search_fields":["warehouse_name"]}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Account','Accounts',0,0,0,1,'{"name":"Account","module":"Accounts","custom":false,"is_submittable":false,"track_changes":true,"fields":[{"fieldname":"account_name","label":"Account Name","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"parent_account","label":"Parent Account","fieldtype":"Link","options":"Account"},{"fieldname":"account_type","label":"Account Type","fieldtype":"Select","options":"Bank\nCash\nReceivable\nPayable\nIncome Account\nExpense Account\nStock\nCost of Goods Sold\nTax\nEquity\nAsset\nLiability","in_list_view":true,"in_standard_filter":true},{"fieldname":"account_currency","label":"Account Currency","fieldtype":"Link","options":"Currency","required":true,"in_list_view":true},{"fieldname":"is_group","label":"Is Group","fieldtype":"Check","default":false,"in_standard_filter":true},{"fieldname":"disabled","label":"Disabled","fieldtype":"Check","default":false,"in_standard_filter":true}],"permissions":[{"role":"System Manager","read":true,"write":true,"create":true,"submit":true,"cancel":true,"amend":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Accounts Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Accounts User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true}],"revision":1,"sort_field":"modified_at","sort_order":"DESC","title_field":"account_name","autoname":"field:name","search_fields":["account_name"]}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Cost Center','Accounts',0,0,0,1,'{"name":"Cost Center","module":"Accounts","custom":false,"is_submittable":false,"track_changes":true,"fields":[{"fieldname":"cost_center_name","label":"Cost Center Name","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"parent_cost_center","label":"Parent Cost Center","fieldtype":"Link","options":"Cost Center"},{"fieldname":"is_group","label":"Is Group","fieldtype":"Check","default":false,"in_standard_filter":true},{"fieldname":"disabled","label":"Disabled","fieldtype":"Check","default":false,"in_standard_filter":true}],"permissions":[{"role":"System Manager","read":true,"write":true,"create":true,"submit":true,"cancel":true,"amend":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Accounts Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Accounts User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true}],"revision":1,"sort_field":"modified_at","sort_order":"DESC","title_field":"cost_center_name","autoname":"field:name","search_fields":["cost_center_name"]}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Project','Projects',0,0,0,1,'{"name":"Project","module":"Projects","custom":false,"is_submittable":false,"track_changes":true,"fields":[{"fieldname":"project_name","label":"Project Name","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"status","label":"Project Status","fieldtype":"Select","options":"Open\nCompleted\nCancelled","default":"Open","in_list_view":true,"in_standard_filter":true},{"fieldname":"expected_start_date","label":"Expected Start","fieldtype":"Date","in_list_view":true},{"fieldname":"expected_end_date","label":"Expected End","fieldtype":"Date","in_list_view":true}],"permissions":[{"role":"System Manager","read":true,"write":true,"create":true,"submit":true,"cancel":true,"amend":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Projects Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Projects User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true},{"role":"Accounts Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true}],"revision":1,"sort_field":"modified_at","sort_order":"DESC","title_field":"project_name","autoname":"PROJ-.YYYY.-#####","search_fields":["project_name"]}',0,'migration','2026-07-25T00:00:00.000Z');

-- Minimal standard print formats.
INSERT OR IGNORE INTO print_formats(tenant_id,name,doc_type,is_default,disabled,revision,format_json,modified_by,modified_at) VALUES('demo','Standard Sales Order','Sales Order',1,0,1,'{"name":"Standard Sales Order","doc_type":"Sales Order","format_type":"Standard","html":"<main><h1>Sales Order</h1><p><strong>{{ name }}</strong></p><p>Status: {{ status }}</p><p>Party: {{ customer }}{{ party }}</p><p>Total: {{ grand_total }}{{ paid_amount }} {{ currency }}</p></main>","css":"body{font-family:system-ui,sans-serif;color:#111}main{max-width:800px;margin:auto}h1{border-bottom:1px solid #ddd;padding-bottom:8px}","is_default":true,"disabled":false,"revision":1}','migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO print_formats(tenant_id,name,doc_type,is_default,disabled,revision,format_json,modified_by,modified_at) VALUES('demo','Standard Delivery Note','Delivery Note',1,0,1,'{"name":"Standard Delivery Note","doc_type":"Delivery Note","format_type":"Standard","html":"<main><h1>Delivery Note</h1><p><strong>{{ name }}</strong></p><p>Status: {{ status }}</p><p>Party: {{ customer }}{{ party }}</p><p>Total: {{ grand_total }}{{ paid_amount }} {{ currency }}</p></main>","css":"body{font-family:system-ui,sans-serif;color:#111}main{max-width:800px;margin:auto}h1{border-bottom:1px solid #ddd;padding-bottom:8px}","is_default":true,"disabled":false,"revision":1}','migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO print_formats(tenant_id,name,doc_type,is_default,disabled,revision,format_json,modified_by,modified_at) VALUES('demo','Standard Sales Invoice','Sales Invoice',1,0,1,'{"name":"Standard Sales Invoice","doc_type":"Sales Invoice","format_type":"Standard","html":"<main><h1>Sales Invoice</h1><p><strong>{{ name }}</strong></p><p>Status: {{ status }}</p><p>Party: {{ customer }}{{ party }}</p><p>Total: {{ grand_total }}{{ paid_amount }} {{ currency }}</p></main>","css":"body{font-family:system-ui,sans-serif;color:#111}main{max-width:800px;margin:auto}h1{border-bottom:1px solid #ddd;padding-bottom:8px}","is_default":true,"disabled":false,"revision":1}','migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO print_formats(tenant_id,name,doc_type,is_default,disabled,revision,format_json,modified_by,modified_at) VALUES('demo','Standard Payment Entry','Payment Entry',1,0,1,'{"name":"Standard Payment Entry","doc_type":"Payment Entry","format_type":"Standard","html":"<main><h1>Payment Entry</h1><p><strong>{{ name }}</strong></p><p>Status: {{ status }}</p><p>Party: {{ customer }}{{ party }}</p><p>Total: {{ grand_total }}{{ paid_amount }} {{ currency }}</p></main>","css":"body{font-family:system-ui,sans-serif;color:#111}main{max-width:800px;margin:auto}h1{border-bottom:1px solid #ddd;padding-bottom:8px}","is_default":true,"disabled":false,"revision":1}','migration','2026-07-25T00:00:00.000Z');


-- Metadata for the four explicit O2C controllers (used by generic UI/print/permission surfaces).
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Sales Order','Selling',0,1,0,1,'{"name":"Sales Order","module":"Selling","is_submittable":true,"track_changes":true,"autoname":"SO-.YYYY.-#####","title_field":"customer","search_fields":["customer"],"sort_field":"transaction_date","sort_order":"DESC","revision":1,"fields":[{"fieldname":"customer","label":"Customer","fieldtype":"Link","options":"Customer","required":true,"in_list_view":true,"in_standard_filter":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"currency","label":"Currency","fieldtype":"Link","options":"Currency","required":true,"in_list_view":true},{"fieldname":"transaction_date","label":"Transaction Date","fieldtype":"Date","required":true,"in_list_view":true},{"fieldname":"items","label":"Items","fieldtype":"Table","options":"Sales Order Item","required":true},{"fieldname":"taxes","label":"Taxes","fieldtype":"Table","options":"Sales Taxes and Charges"},{"fieldname":"grand_total","label":"Grand Total","fieldtype":"Currency","read_only":true,"in_list_view":true},{"fieldname":"delivered_percentage","label":"Delivered %","fieldtype":"Percent","read_only":true},{"fieldname":"billed_percentage","label":"Billed %","fieldtype":"Percent","read_only":true}],"permissions":[{"role":"Sales Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Sales User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Delivery Note','Stock',0,1,0,1,'{"name":"Delivery Note","module":"Stock","is_submittable":true,"track_changes":true,"autoname":"DN-.YYYY.-#####","title_field":"customer","search_fields":["customer","against_sales_order"],"sort_field":"posting_at","sort_order":"DESC","revision":1,"fields":[{"fieldname":"customer","label":"Customer","fieldtype":"Link","options":"Customer","required":true,"in_list_view":true,"in_standard_filter":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true},{"fieldname":"currency","label":"Currency","fieldtype":"Link","options":"Currency","required":true},{"fieldname":"posting_at","label":"Posting At","fieldtype":"Datetime","required":true,"in_list_view":true},{"fieldname":"against_sales_order","label":"Sales Order","fieldtype":"Link","options":"Sales Order","required":true,"in_list_view":true,"search_index":true},{"fieldname":"items","label":"Items","fieldtype":"Table","options":"Delivery Note Item","required":true}],"permissions":[{"role":"Sales Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Sales User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"Stock Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Stock User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Sales Invoice','Accounts',0,1,0,1,'{"name":"Sales Invoice","module":"Accounts","is_submittable":true,"track_changes":true,"autoname":"SI-.YYYY.-#####","title_field":"customer","search_fields":["customer","against_sales_order"],"sort_field":"posting_at","sort_order":"DESC","revision":1,"fields":[{"fieldname":"customer","label":"Customer","fieldtype":"Link","options":"Customer","required":true,"in_list_view":true,"in_standard_filter":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true},{"fieldname":"currency","label":"Currency","fieldtype":"Link","options":"Currency","required":true},{"fieldname":"posting_at","label":"Posting At","fieldtype":"Datetime","required":true,"in_list_view":true},{"fieldname":"against_sales_order","label":"Sales Order","fieldtype":"Link","options":"Sales Order","required":true,"in_list_view":true,"search_index":true},{"fieldname":"items","label":"Items","fieldtype":"Table","options":"Sales Invoice Item","required":true},{"fieldname":"taxes","label":"Taxes","fieldtype":"Table","options":"Sales Taxes and Charges"},{"fieldname":"grand_total","label":"Grand Total","fieldtype":"Currency","read_only":true,"in_list_view":true},{"fieldname":"outstanding_amount","label":"Outstanding","fieldtype":"Currency","read_only":true,"in_list_view":true}],"permissions":[{"role":"Accounts Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Accounts User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"Sales Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"Sales User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Payment Entry','Accounts',0,1,0,1,'{"name":"Payment Entry","module":"Accounts","is_submittable":true,"track_changes":true,"autoname":"PE-.YYYY.-#####","title_field":"party","search_fields":["party"],"sort_field":"posting_at","sort_order":"DESC","revision":1,"fields":[{"fieldname":"payment_type","label":"Payment Type","fieldtype":"Select","options":"Receive\nPay\nInternal Transfer","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"party_type","label":"Party Type","fieldtype":"Select","options":"Customer\nSupplier","required":true,"in_list_view":true},{"fieldname":"party","label":"Party","fieldtype":"Dynamic Link","options":"party_type","required":true,"in_list_view":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true},{"fieldname":"currency","label":"Currency","fieldtype":"Link","options":"Currency","required":true},{"fieldname":"posting_at","label":"Posting At","fieldtype":"Datetime","required":true,"in_list_view":true},{"fieldname":"paid_amount","label":"Paid Amount","fieldtype":"Currency","required":true,"in_list_view":true},{"fieldname":"references","label":"References","fieldtype":"Table","options":"Payment Entry Reference","required":true}],"permissions":[{"role":"Accounts Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Accounts User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
