-- Core Accounting, Buying and Stock verticals.
CREATE TABLE IF NOT EXISTS purchase_order_progress_entries (
  tenant_id TEXT NOT NULL,
  voucher_type TEXT NOT NULL,
  voucher_no TEXT NOT NULL,
  voucher_revision INTEGER NOT NULL,
  line_key TEXT NOT NULL,
  purchase_order TEXT NOT NULL,
  kind TEXT NOT NULL CHECK (kind IN ('Receipt','Billing')),
  item_code TEXT NOT NULL,
  qty_micros INTEGER NOT NULL,
  posting_at TEXT NOT NULL,
  PRIMARY KEY (tenant_id,voucher_type,voucher_no,voucher_revision,line_key)
);
CREATE INDEX IF NOT EXISTS idx_po_progress_reference ON purchase_order_progress_entries(tenant_id,purchase_order,kind,item_code,posting_at);

CREATE TRIGGER IF NOT EXISTS purchase_progress_reference_guard
BEFORE INSERT ON purchase_order_progress_entries
BEGIN
  SELECT CASE
    WHEN NOT EXISTS (
      SELECT 1 FROM documents WHERE tenant_id=NEW.tenant_id
        AND doc_key='Purchase Order:' || NEW.purchase_order AND doctype='Purchase Order' AND docstatus=1
    ) THEN RAISE(ABORT,'PURCHASE_REFERENCE_SOURCE_NOT_FOUND')
    WHEN NOT EXISTS (
      SELECT 1 FROM document_children WHERE tenant_id=NEW.tenant_id
        AND parent_key='Purchase Order:' || NEW.purchase_order AND fieldname='items'
        AND json_extract(payload_json,'$.item_code')=NEW.item_code
    ) THEN RAISE(ABORT,'PURCHASE_REFERENCE_ITEM_NOT_FOUND')
    WHEN COALESCE((SELECT SUM(qty_micros) FROM purchase_order_progress_entries
      WHERE tenant_id=NEW.tenant_id AND purchase_order=NEW.purchase_order AND kind=NEW.kind AND item_code=NEW.item_code),0)+NEW.qty_micros < 0
      THEN RAISE(ABORT,'PURCHASE_REFERENCE_QUANTITY_NEGATIVE')
    WHEN COALESCE((SELECT SUM(qty_micros) FROM purchase_order_progress_entries
      WHERE tenant_id=NEW.tenant_id AND purchase_order=NEW.purchase_order AND kind=NEW.kind AND item_code=NEW.item_code),0)+NEW.qty_micros >
      (SELECT COALESCE(SUM(CAST(json_extract(payload_json,'$.qty_micros') AS INTEGER)),0) FROM document_children
       WHERE tenant_id=NEW.tenant_id AND parent_key='Purchase Order:' || NEW.purchase_order AND fieldname='items'
       AND json_extract(payload_json,'$.item_code')=NEW.item_code)
      THEN RAISE(ABORT,'PURCHASE_REFERENCE_QUANTITY_EXCEEDED')
  END;
END;

CREATE TRIGGER IF NOT EXISTS purchase_order_cancel_reference_guard
BEFORE INSERT ON mutation_guard
WHEN NEW.action='cancel'
 AND (SELECT doctype FROM documents WHERE tenant_id=NEW.tenant_id AND doc_key=NEW.doc_key)='Purchase Order'
 AND COALESCE((SELECT SUM(qty_micros) FROM purchase_order_progress_entries WHERE tenant_id=NEW.tenant_id
   AND purchase_order=(SELECT name FROM documents WHERE tenant_id=NEW.tenant_id AND doc_key=NEW.doc_key)),0) != 0
BEGIN SELECT RAISE(ABORT,'ACTIVE_PURCHASE_PROGRESS_EXISTS'); END;

CREATE TRIGGER IF NOT EXISTS purchase_invoice_cancel_payment_guard
BEFORE INSERT ON mutation_guard
WHEN NEW.action='cancel'
 AND (SELECT doctype FROM documents WHERE tenant_id=NEW.tenant_id AND doc_key=NEW.doc_key)='Purchase Invoice'
 AND COALESCE((SELECT SUM(amount_minor) FROM payment_ledger_entries WHERE tenant_id=NEW.tenant_id
   AND against_voucher_type='Purchase Invoice' AND against_voucher_no=(SELECT name FROM documents WHERE tenant_id=NEW.tenant_id AND doc_key=NEW.doc_key)),0)
   != COALESCE(CAST((SELECT json_extract(payload_json,'$.grand_total_minor') FROM documents WHERE tenant_id=NEW.tenant_id AND doc_key=NEW.doc_key) AS INTEGER),0)
BEGIN SELECT RAISE(ABORT,'ACTIVE_SUPPLIER_PAYMENT_ALLOCATIONS'); END;

CREATE VIEW IF NOT EXISTS payable_outstanding AS
SELECT tenant_id,party,currency,currency_scale,against_voucher_type,against_voucher_no,
       SUM(amount_minor) AS outstanding_minor,SUM(base_amount_minor) AS base_outstanding_minor,
       CAST(SUM(amount_minor) AS REAL)/CASE currency_scale WHEN 0 THEN 1 WHEN 1 THEN 10 WHEN 2 THEN 100 WHEN 3 THEN 1000 WHEN 4 THEN 10000 WHEN 5 THEN 100000 ELSE 1000000 END AS outstanding_amount
FROM payment_ledger_entries WHERE account_type='Payable'
GROUP BY tenant_id,party,currency,currency_scale,against_voucher_type,against_voucher_no;

CREATE VIEW IF NOT EXISTS general_ledger_report AS
SELECT tenant_id,posting_at,voucher_type,voucher_no,account,party_type,party,currency,currency_scale,
       CAST(debit_minor AS REAL)/CASE currency_scale WHEN 0 THEN 1 WHEN 1 THEN 10 WHEN 2 THEN 100 WHEN 3 THEN 1000 WHEN 4 THEN 10000 WHEN 5 THEN 100000 ELSE 1000000 END AS debit,
       CAST(credit_minor AS REAL)/CASE currency_scale WHEN 0 THEN 1 WHEN 1 THEN 10 WHEN 2 THEN 100 WHEN 3 THEN 1000 WHEN 4 THEN 10000 WHEN 5 THEN 100000 ELSE 1000000 END AS credit,
       cost_center
FROM gl_entries;

CREATE VIEW IF NOT EXISTS trial_balance AS
SELECT tenant_id,account,currency,currency_scale,
       CAST(SUM(debit_minor) AS REAL)/CASE currency_scale WHEN 0 THEN 1 WHEN 1 THEN 10 WHEN 2 THEN 100 WHEN 3 THEN 1000 WHEN 4 THEN 10000 WHEN 5 THEN 100000 ELSE 1000000 END AS debit,
       CAST(SUM(credit_minor) AS REAL)/CASE currency_scale WHEN 0 THEN 1 WHEN 1 THEN 10 WHEN 2 THEN 100 WHEN 3 THEN 1000 WHEN 4 THEN 10000 WHEN 5 THEN 100000 ELSE 1000000 END AS credit,
       CAST(SUM(debit_minor-credit_minor) AS REAL)/CASE currency_scale WHEN 0 THEN 1 WHEN 1 THEN 10 WHEN 2 THEN 100 WHEN 3 THEN 1000 WHEN 4 THEN 10000 WHEN 5 THEN 100000 ELSE 1000000 END AS balance
FROM gl_entries GROUP BY tenant_id,account,currency,currency_scale;

-- Standard metadata for core ERP verticals.
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Journal Entry','Accounts',0,1,0,1,'{"name":"Journal Entry","module":"Accounts","is_submittable":true,"track_changes":true,"autoname":"JV-.YYYY.-#####","sort_field":"posting_at","sort_order":"DESC","revision":1,"fields":[{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"posting_at","label":"Posting At","fieldtype":"Datetime","required":true,"in_list_view":true},{"fieldname":"voucher_type","label":"Voucher Type","fieldtype":"Select","options":"Journal Entry\nBank Entry\nCash Entry\nOpening Entry\nCredit Card Entry\nExchange Gain Or Loss","default":"Journal Entry","in_list_view":true,"in_standard_filter":true},{"fieldname":"user_remark","label":"Remark","fieldtype":"Small Text"},{"fieldname":"accounts","label":"Accounts","fieldtype":"Table","options":"Journal Entry Account","required":true},{"fieldname":"total_debit","label":"Total Debit","fieldtype":"Currency","read_only":true,"in_list_view":true},{"fieldname":"total_credit","label":"Total Credit","fieldtype":"Currency","read_only":true,"in_list_view":true}],"permissions":[{"role":"Accounts Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Accounts User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Purchase Order','Buying',0,1,0,1,'{"name":"Purchase Order","module":"Buying","is_submittable":true,"track_changes":true,"autoname":"PO-.YYYY.-#####","title_field":"supplier","search_fields":["supplier"],"sort_field":"transaction_date","sort_order":"DESC","revision":1,"fields":[{"fieldname":"supplier","label":"Supplier","fieldtype":"Link","options":"Supplier","required":true,"in_list_view":true,"in_standard_filter":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"currency","label":"Currency","fieldtype":"Link","options":"Currency","required":true,"in_list_view":true},{"fieldname":"transaction_date","label":"Transaction Date","fieldtype":"Date","required":true,"in_list_view":true},{"fieldname":"schedule_date","label":"Schedule Date","fieldtype":"Date","in_list_view":true},{"fieldname":"items","label":"Items","fieldtype":"Table","options":"Purchase Order Item","required":true},{"fieldname":"taxes","label":"Taxes","fieldtype":"Table","options":"Purchase Taxes and Charges"},{"fieldname":"grand_total","label":"Grand Total","fieldtype":"Currency","read_only":true,"in_list_view":true},{"fieldname":"received_percentage","label":"Received %","fieldtype":"Percent","read_only":true},{"fieldname":"billed_percentage","label":"Billed %","fieldtype":"Percent","read_only":true}],"permissions":[{"role":"Purchase Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Purchase User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Purchase Receipt','Stock',0,1,0,1,'{"name":"Purchase Receipt","module":"Stock","is_submittable":true,"track_changes":true,"autoname":"PR-.YYYY.-#####","title_field":"supplier","search_fields":["supplier","against_purchase_order"],"sort_field":"posting_at","sort_order":"DESC","revision":1,"fields":[{"fieldname":"supplier","label":"Supplier","fieldtype":"Link","options":"Supplier","required":true,"in_list_view":true,"in_standard_filter":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true},{"fieldname":"currency","label":"Currency","fieldtype":"Link","options":"Currency","required":true},{"fieldname":"posting_at","label":"Posting At","fieldtype":"Datetime","required":true,"in_list_view":true},{"fieldname":"against_purchase_order","label":"Purchase Order","fieldtype":"Link","options":"Purchase Order","required":true,"in_list_view":true,"search_index":true},{"fieldname":"items","label":"Items","fieldtype":"Table","options":"Purchase Receipt Item","required":true}],"permissions":[{"role":"Purchase Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Purchase User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"Stock Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Stock User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Purchase Invoice','Accounts',0,1,0,1,'{"name":"Purchase Invoice","module":"Accounts","is_submittable":true,"track_changes":true,"autoname":"PINV-.YYYY.-#####","title_field":"supplier","search_fields":["supplier","against_purchase_order"],"sort_field":"posting_at","sort_order":"DESC","revision":1,"fields":[{"fieldname":"supplier","label":"Supplier","fieldtype":"Link","options":"Supplier","required":true,"in_list_view":true,"in_standard_filter":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true},{"fieldname":"currency","label":"Currency","fieldtype":"Link","options":"Currency","required":true},{"fieldname":"posting_at","label":"Posting At","fieldtype":"Datetime","required":true,"in_list_view":true},{"fieldname":"due_date","label":"Due Date","fieldtype":"Date","in_list_view":true},{"fieldname":"against_purchase_order","label":"Purchase Order","fieldtype":"Link","options":"Purchase Order","in_list_view":true,"search_index":true},{"fieldname":"credit_to","label":"Payable Account","fieldtype":"Link","options":"Account","required":true},{"fieldname":"items","label":"Items","fieldtype":"Table","options":"Purchase Invoice Item","required":true},{"fieldname":"taxes","label":"Taxes","fieldtype":"Table","options":"Purchase Taxes and Charges"},{"fieldname":"grand_total","label":"Grand Total","fieldtype":"Currency","read_only":true,"in_list_view":true},{"fieldname":"outstanding_amount","label":"Outstanding","fieldtype":"Currency","read_only":true,"in_list_view":true}],"permissions":[{"role":"Accounts Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Accounts User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"Purchase Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"Purchase User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Stock Entry','Stock',0,1,0,1,'{"name":"Stock Entry","module":"Stock","is_submittable":true,"track_changes":true,"autoname":"STE-.YYYY.-#####","sort_field":"posting_at","sort_order":"DESC","revision":1,"fields":[{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"posting_at","label":"Posting At","fieldtype":"Datetime","required":true,"in_list_view":true},{"fieldname":"purpose","label":"Purpose","fieldtype":"Select","options":"Material Receipt\nMaterial Issue\nMaterial Transfer","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"items","label":"Items","fieldtype":"Table","options":"Stock Entry Detail","required":true}],"permissions":[{"role":"Stock Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Stock User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Journal Entry Account','Accounts',0,0,1,1,'{"name":"Journal Entry Account","module":"Accounts","is_child":true,"revision":1,"fields":[{"fieldname":"account","label":"Account","fieldtype":"Link","options":"Account","required":true,"in_list_view":true},{"fieldname":"party_type","label":"Party Type","fieldtype":"Select","options":"Customer\nSupplier"},{"fieldname":"party","label":"Party","fieldtype":"Dynamic Link","options":"party_type"},{"fieldname":"debit","label":"Debit","fieldtype":"Currency","default":"0"},{"fieldname":"credit","label":"Credit","fieldtype":"Currency","default":"0"},{"fieldname":"cost_center","label":"Cost Center","fieldtype":"Link","options":"Cost Center"}],"permissions":[],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Purchase Order Item','Buying',0,0,1,1,'{"name":"Purchase Order Item","module":"Buying","is_child":true,"revision":1,"fields":[{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","required":true,"in_list_view":true},{"fieldname":"qty","label":"Qty","fieldtype":"Float","required":true,"in_list_view":true},{"fieldname":"rate","label":"Rate","fieldtype":"Currency","required":true,"in_list_view":true},{"fieldname":"warehouse","label":"Warehouse","fieldtype":"Link","options":"Warehouse"},{"fieldname":"expense_account","label":"Expense Account","fieldtype":"Link","options":"Account"}],"permissions":[],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Purchase Receipt Item','Stock',0,0,1,1,'{"name":"Purchase Receipt Item","module":"Stock","is_child":true,"revision":1,"fields":[{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","required":true},{"fieldname":"qty","label":"Qty","fieldtype":"Float","required":true},{"fieldname":"rate","label":"Rate","fieldtype":"Currency","required":true},{"fieldname":"valuation_rate","label":"Valuation Rate","fieldtype":"Currency"},{"fieldname":"warehouse","label":"Warehouse","fieldtype":"Link","options":"Warehouse","required":true}],"permissions":[],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Purchase Invoice Item','Accounts',0,0,1,1,'{"name":"Purchase Invoice Item","module":"Accounts","is_child":true,"revision":1,"fields":[{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","required":true},{"fieldname":"qty","label":"Qty","fieldtype":"Float","required":true},{"fieldname":"rate","label":"Rate","fieldtype":"Currency","required":true},{"fieldname":"expense_account","label":"Expense Account","fieldtype":"Link","options":"Account","required":true},{"fieldname":"warehouse","label":"Warehouse","fieldtype":"Link","options":"Warehouse"}],"permissions":[],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR IGNORE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Stock Entry Detail','Stock',0,0,1,1,'{"name":"Stock Entry Detail","module":"Stock","is_child":true,"revision":1,"fields":[{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","required":true},{"fieldname":"qty","label":"Qty","fieldtype":"Float","required":true},{"fieldname":"source_warehouse","label":"Source Warehouse","fieldtype":"Link","options":"Warehouse"},{"fieldname":"target_warehouse","label":"Target Warehouse","fieldtype":"Link","options":"Warehouse"},{"fieldname":"valuation_rate","label":"Valuation Rate","fieldtype":"Currency","required":true}],"permissions":[],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');

-- Immutable standard catalog source. Tenant provisioning copies from this
-- catalog so non-demo Workers do not depend on hard-coded demo metadata.
INSERT OR IGNORE INTO doctype_definitions
SELECT '__standard__',doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at
FROM doctype_definitions WHERE tenant_id='demo';
INSERT OR IGNORE INTO print_formats
SELECT '__standard__',name,doc_type,is_default,disabled,revision,format_json,modified_by,modified_at
FROM print_formats WHERE tenant_id='demo';
