-- ERPNext Core: valuation/repost support, serial-batch integrity, returns,
-- manufacturing progress and asset depreciation projections.

CREATE TABLE IF NOT EXISTS stock_bundle_usage_entries (
  tenant_id TEXT NOT NULL,
  voucher_type TEXT NOT NULL,
  voucher_no TEXT NOT NULL,
  voucher_revision INTEGER NOT NULL,
  line_key TEXT NOT NULL,
  bundle_name TEXT NOT NULL,
  item_code TEXT NOT NULL,
  warehouse TEXT NOT NULL,
  direction TEXT NOT NULL CHECK(direction IN ('Inward','Outward')),
  usage_delta INTEGER NOT NULL CHECK(usage_delta IN (-1,1)),
  posting_at TEXT NOT NULL,
  PRIMARY KEY(tenant_id,voucher_type,voucher_no,voucher_revision,line_key)
);
CREATE INDEX IF NOT EXISTS idx_bundle_usage_voucher
  ON stock_bundle_usage_entries(tenant_id,voucher_type,voucher_no,voucher_revision);

CREATE TRIGGER IF NOT EXISTS stock_bundle_source_guard
BEFORE INSERT ON stock_bundle_usage_entries
BEGIN
  SELECT CASE
    WHEN NOT EXISTS (
      SELECT 1 FROM documents WHERE tenant_id=NEW.tenant_id
       AND doc_key='Serial and Batch Bundle:' || NEW.bundle_name
       AND doctype='Serial and Batch Bundle' AND docstatus=1
    ) THEN RAISE(ABORT,'SERIAL_BATCH_BUNDLE_NOT_SUBMITTED')
    WHEN COALESCE((SELECT SUM(usage_delta) FROM stock_bundle_usage_entries
      WHERE tenant_id=NEW.tenant_id AND bundle_name=NEW.bundle_name),0)+NEW.usage_delta NOT IN (0,1)
      THEN RAISE(ABORT,'SERIAL_BATCH_BUNDLE_USAGE_INVALID')
  END;
END;

-- Serial stock is globally unique per item and may only be absent (0) or present
-- as exactly one unit (1e6 quantity micros). This remains fail-closed even when
-- a voucher otherwise permits negative untracked stock.
CREATE TRIGGER IF NOT EXISTS serial_stock_integrity_guard
BEFORE INSERT ON stock_ledger_entries
WHEN NEW.serial_no IS NOT NULL
BEGIN
  SELECT CASE
    WHEN ABS(NEW.actual_qty_micros) <> 1000000
      THEN RAISE(ABORT,'SERIAL_QUANTITY_MUST_EQUAL_ONE')
    WHEN COALESCE((SELECT SUM(actual_qty_micros) FROM stock_ledger_entries
      WHERE tenant_id=NEW.tenant_id AND item_code=NEW.item_code AND serial_no=NEW.serial_no),0)
      + NEW.actual_qty_micros NOT IN (0,1000000)
      THEN RAISE(ABORT,'SERIAL_STOCK_STATE_INVALID')
  END;
END;

CREATE TRIGGER IF NOT EXISTS batch_stock_integrity_guard
BEFORE INSERT ON stock_ledger_entries
WHEN NEW.batch_no IS NOT NULL
 AND COALESCE((SELECT SUM(actual_qty_micros) FROM stock_ledger_entries
   WHERE tenant_id=NEW.tenant_id AND item_code=NEW.item_code
     AND warehouse=NEW.warehouse AND batch_no=NEW.batch_no),0) + NEW.actual_qty_micros < 0
BEGIN
  SELECT RAISE(ABORT,'BATCH_NEGATIVE_STOCK');
END;

CREATE TABLE IF NOT EXISTS return_progress_entries (
  tenant_id TEXT NOT NULL,
  voucher_type TEXT NOT NULL,
  voucher_no TEXT NOT NULL,
  voucher_revision INTEGER NOT NULL,
  line_key TEXT NOT NULL,
  reference_doctype TEXT NOT NULL CHECK(reference_doctype IN ('Sales Invoice','Purchase Invoice','Delivery Note','Purchase Receipt')),
  reference_name TEXT NOT NULL,
  kind TEXT NOT NULL CHECK(kind IN ('Sales Credit','Purchase Debit','Sales Stock','Purchase Stock')),
  item_code TEXT NOT NULL,
  qty_micros INTEGER NOT NULL,
  posting_at TEXT NOT NULL,
  PRIMARY KEY(tenant_id,voucher_type,voucher_no,voucher_revision,line_key)
);
CREATE INDEX IF NOT EXISTS idx_return_reference
 ON return_progress_entries(tenant_id,reference_doctype,reference_name,kind,item_code,posting_at);

CREATE TRIGGER IF NOT EXISTS return_progress_guard
BEFORE INSERT ON return_progress_entries
BEGIN
  SELECT CASE
    WHEN NOT EXISTS (
      SELECT 1 FROM documents WHERE tenant_id=NEW.tenant_id
       AND doc_key=NEW.reference_doctype || ':' || NEW.reference_name
       AND doctype=NEW.reference_doctype AND docstatus=1
    ) THEN RAISE(ABORT,'RETURN_REFERENCE_NOT_SUBMITTED')
    WHEN NOT EXISTS (
      SELECT 1 FROM document_children WHERE tenant_id=NEW.tenant_id
       AND parent_key=NEW.reference_doctype || ':' || NEW.reference_name
       AND fieldname='items' AND json_extract(payload_json,'$.item_code')=NEW.item_code
    ) THEN RAISE(ABORT,'RETURN_REFERENCE_ITEM_NOT_FOUND')
    WHEN COALESCE((SELECT SUM(qty_micros) FROM return_progress_entries
      WHERE tenant_id=NEW.tenant_id AND reference_doctype=NEW.reference_doctype
       AND reference_name=NEW.reference_name AND kind=NEW.kind AND item_code=NEW.item_code),0)
       + NEW.qty_micros < 0
      THEN RAISE(ABORT,'RETURN_QUANTITY_NEGATIVE')
    WHEN COALESCE((SELECT SUM(qty_micros) FROM return_progress_entries
      WHERE tenant_id=NEW.tenant_id AND reference_doctype=NEW.reference_doctype
       AND reference_name=NEW.reference_name AND kind=NEW.kind AND item_code=NEW.item_code),0)
       + NEW.qty_micros >
      (SELECT COALESCE(SUM(CAST(json_extract(payload_json,'$.qty_micros') AS INTEGER)),0)
       FROM document_children WHERE tenant_id=NEW.tenant_id
        AND parent_key=NEW.reference_doctype || ':' || NEW.reference_name
        AND fieldname='items' AND json_extract(payload_json,'$.item_code')=NEW.item_code)
      THEN RAISE(ABORT,'RETURN_QUANTITY_EXCEEDED')
  END;
END;

CREATE TABLE IF NOT EXISTS manufacturing_progress_entries (
  tenant_id TEXT NOT NULL,
  voucher_type TEXT NOT NULL,
  voucher_no TEXT NOT NULL,
  voucher_revision INTEGER NOT NULL,
  line_key TEXT NOT NULL,
  work_order TEXT NOT NULL,
  kind TEXT NOT NULL CHECK(kind IN ('Material Transfer','Consumption','Manufacture')),
  item_code TEXT NOT NULL,
  qty_micros INTEGER NOT NULL,
  posting_at TEXT NOT NULL,
  PRIMARY KEY(tenant_id,voucher_type,voucher_no,voucher_revision,line_key)
);
CREATE INDEX IF NOT EXISTS idx_manufacturing_reference
 ON manufacturing_progress_entries(tenant_id,work_order,kind,item_code,posting_at);

CREATE TRIGGER IF NOT EXISTS manufacturing_progress_guard
BEFORE INSERT ON manufacturing_progress_entries
BEGIN
  SELECT CASE
    WHEN NOT EXISTS (
      SELECT 1 FROM documents WHERE tenant_id=NEW.tenant_id
       AND doc_key='Work Order:' || NEW.work_order AND doctype='Work Order' AND docstatus=1
    ) THEN RAISE(ABORT,'WORK_ORDER_NOT_SUBMITTED')
    WHEN COALESCE((SELECT SUM(qty_micros) FROM manufacturing_progress_entries
      WHERE tenant_id=NEW.tenant_id AND work_order=NEW.work_order
       AND kind=NEW.kind AND item_code=NEW.item_code),0)+NEW.qty_micros < 0
      THEN RAISE(ABORT,'MANUFACTURING_PROGRESS_NEGATIVE')
    WHEN NEW.kind='Manufacture' AND
      COALESCE((SELECT SUM(qty_micros) FROM manufacturing_progress_entries
       WHERE tenant_id=NEW.tenant_id AND work_order=NEW.work_order
        AND kind='Manufacture' AND item_code=NEW.item_code),0)+NEW.qty_micros >
      COALESCE(CAST((SELECT json_extract(payload_json,'$.qty_micros') FROM documents
       WHERE tenant_id=NEW.tenant_id AND doc_key='Work Order:' || NEW.work_order) AS INTEGER),0)
      THEN RAISE(ABORT,'WORK_ORDER_OVER_PRODUCTION')
    WHEN NEW.kind IN ('Material Transfer','Consumption') AND
      COALESCE((SELECT SUM(qty_micros) FROM manufacturing_progress_entries
       WHERE tenant_id=NEW.tenant_id AND work_order=NEW.work_order
        AND kind=NEW.kind AND item_code=NEW.item_code),0)+NEW.qty_micros >
      COALESCE((SELECT SUM(CAST(json_extract(payload_json,'$.required_qty_micros') AS INTEGER))
       FROM document_children WHERE tenant_id=NEW.tenant_id
        AND parent_key='Work Order:' || NEW.work_order AND fieldname='required_items'
        AND json_extract(payload_json,'$.item_code')=NEW.item_code),0)
      THEN RAISE(ABORT,'WORK_ORDER_MATERIAL_EXCEEDED')
  END;
END;

CREATE TABLE IF NOT EXISTS asset_depreciation_entries (
  tenant_id TEXT NOT NULL,
  voucher_type TEXT NOT NULL,
  voucher_no TEXT NOT NULL,
  voucher_revision INTEGER NOT NULL,
  line_key TEXT NOT NULL,
  asset TEXT NOT NULL,
  amount_minor INTEGER NOT NULL CHECK(amount_minor<>0),
  currency TEXT NOT NULL,
  currency_scale INTEGER NOT NULL CHECK(currency_scale BETWEEN 0 AND 6),
  posting_at TEXT NOT NULL,
  PRIMARY KEY(tenant_id,voucher_type,voucher_no,voucher_revision,line_key)
);
CREATE INDEX IF NOT EXISTS idx_asset_depreciation_reference
 ON asset_depreciation_entries(tenant_id,asset,posting_at);

CREATE TRIGGER IF NOT EXISTS asset_depreciation_guard
BEFORE INSERT ON asset_depreciation_entries
BEGIN
  SELECT CASE
    WHEN NOT EXISTS (
      SELECT 1 FROM documents WHERE tenant_id=NEW.tenant_id
       AND doc_key='Asset:' || NEW.asset AND doctype='Asset' AND docstatus<>2
    ) THEN RAISE(ABORT,'ASSET_NOT_ACTIVE')
    WHEN COALESCE((SELECT SUM(amount_minor) FROM asset_depreciation_entries
      WHERE tenant_id=NEW.tenant_id AND asset=NEW.asset),0)+NEW.amount_minor < 0
      THEN RAISE(ABORT,'ASSET_DEPRECIATION_NEGATIVE')
    WHEN COALESCE((SELECT SUM(amount_minor) FROM asset_depreciation_entries
      WHERE tenant_id=NEW.tenant_id AND asset=NEW.asset),0)+NEW.amount_minor >
      COALESCE(CAST((SELECT json_extract(payload_json,'$.gross_purchase_amount_minor') FROM documents
       WHERE tenant_id=NEW.tenant_id AND doc_key='Asset:' || NEW.asset) AS INTEGER),0)
      - COALESCE(CAST((SELECT json_extract(payload_json,'$.salvage_value_minor') FROM documents
       WHERE tenant_id=NEW.tenant_id AND doc_key='Asset:' || NEW.asset) AS INTEGER),0)
      THEN RAISE(ABORT,'ASSET_DEPRECIATION_EXCEEDED')
  END;
END;

CREATE VIEW IF NOT EXISTS stock_ledger_report AS
SELECT tenant_id,posting_at,voucher_type,voucher_no,item_code,warehouse,batch_no,serial_no,currency,currency_scale,
       CAST(actual_qty_micros AS REAL)/1000000.0 AS actual_qty,
       CAST(valuation_rate_minor AS REAL)/CASE currency_scale WHEN 0 THEN 1 WHEN 1 THEN 10 WHEN 2 THEN 100 WHEN 3 THEN 1000 WHEN 4 THEN 10000 WHEN 5 THEN 100000 ELSE 1000000 END AS valuation_rate,
       CAST(stock_value_difference_minor AS REAL)/CASE currency_scale WHEN 0 THEN 1 WHEN 1 THEN 10 WHEN 2 THEN 100 WHEN 3 THEN 1000 WHEN 4 THEN 10000 WHEN 5 THEN 100000 ELSE 1000000 END AS stock_value_difference
FROM stock_ledger_entries;

CREATE VIEW IF NOT EXISTS batch_stock_balance AS
SELECT tenant_id,item_code,warehouse,batch_no,currency,currency_scale,
       SUM(actual_qty_micros) AS actual_qty_micros,
       CAST(SUM(actual_qty_micros) AS REAL)/1000000.0 AS actual_qty,
       SUM(stock_value_difference_minor) AS stock_value_minor,
       CAST(SUM(stock_value_difference_minor) AS REAL)/CASE currency_scale WHEN 0 THEN 1 WHEN 1 THEN 10 WHEN 2 THEN 100 WHEN 3 THEN 1000 WHEN 4 THEN 10000 WHEN 5 THEN 100000 ELSE 1000000 END AS stock_value
FROM stock_ledger_entries WHERE batch_no IS NOT NULL
GROUP BY tenant_id,item_code,warehouse,batch_no,currency,currency_scale;

CREATE VIEW IF NOT EXISTS serial_stock_state AS
SELECT tenant_id,item_code,serial_no,
       SUM(actual_qty_micros) AS actual_qty_micros,
       CAST(SUM(actual_qty_micros) AS REAL)/1000000.0 AS actual_qty,
       CASE WHEN SUM(actual_qty_micros)=1000000 THEN 'Available' ELSE 'Delivered' END AS status,
       MAX(CASE WHEN actual_qty_micros>0 THEN warehouse ELSE NULL END) AS last_inward_warehouse,
       MAX(posting_at) AS last_posting_at
FROM stock_ledger_entries WHERE serial_no IS NOT NULL
GROUP BY tenant_id,item_code,serial_no;

CREATE VIEW IF NOT EXISTS work_order_progress AS
SELECT d.tenant_id,d.name AS work_order,
       json_extract(d.payload_json,'$.production_item') AS production_item,
       json_extract(d.payload_json,'$.target_warehouse') AS target_warehouse,
       CAST(COALESCE(json_extract(d.payload_json,'$.qty_micros'),0) AS REAL)/1000000.0 AS planned_qty,
       CAST(COALESCE(SUM(CASE WHEN m.kind='Manufacture' THEN m.qty_micros ELSE 0 END),0) AS REAL)/1000000.0 AS produced_qty,
       CASE WHEN COALESCE(SUM(CASE WHEN m.kind='Manufacture' THEN m.qty_micros ELSE 0 END),0)>=COALESCE(json_extract(d.payload_json,'$.qty_micros'),0) THEN 'Completed'
            WHEN COALESCE(SUM(CASE WHEN m.kind='Manufacture' THEN m.qty_micros ELSE 0 END),0)>0 THEN 'In Process'
            ELSE d.status END AS status
FROM documents d LEFT JOIN manufacturing_progress_entries m
 ON m.tenant_id=d.tenant_id AND m.work_order=d.name
WHERE d.doctype='Work Order'
GROUP BY d.tenant_id,d.name,d.payload_json,d.status;

CREATE VIEW IF NOT EXISTS asset_depreciation_ledger AS
SELECT tenant_id,posting_at,voucher_no,asset,currency,currency_scale,
       CAST(amount_minor AS REAL)/CASE currency_scale WHEN 0 THEN 1 WHEN 1 THEN 10 WHEN 2 THEN 100 WHEN 3 THEN 1000 WHEN 4 THEN 10000 WHEN 5 THEN 100000 ELSE 1000000 END AS amount
FROM asset_depreciation_entries;

CREATE VIEW IF NOT EXISTS asset_depreciation_balance AS
SELECT tenant_id,asset,SUM(amount_minor) AS depreciated_minor,MAX(posting_at) AS last_posting_at
FROM asset_depreciation_entries GROUP BY tenant_id,asset;


-- BEGIN ERPNext Core standard metadata v0.8
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Serial and Batch Bundle','Stock',0,1,0,1,'{"name":"Serial and Batch Bundle","module":"Stock","is_submittable":true,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","required":true,"in_list_view":true,"search_index":true},{"fieldname":"warehouse","label":"Warehouse","fieldtype":"Link","options":"Warehouse","required":true,"in_list_view":true},{"fieldname":"type","label":"Type","fieldtype":"Select","options":"Inward\nOutward","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"posting_at","label":"Posting At","fieldtype":"Datetime","required":true,"in_list_view":true},{"fieldname":"entries","label":"Entries","fieldtype":"Table","options":"Serial and Batch Bundle Entry","required":true},{"fieldname":"total_qty","label":"Total Qty","fieldtype":"Float","read_only":true,"in_list_view":true}],"permissions":[{"role":"Stock Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Stock User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"SABB-.YYYY.-#####","search_fields":["item_code","warehouse"],"sort_field":"posting_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Serial and Batch Bundle Entry','Stock',0,0,1,1,'{"name":"Serial and Batch Bundle Entry","module":"Stock","is_submittable":false,"is_child":true,"track_changes":false,"revision":1,"fields":[{"fieldname":"qty","label":"Qty","fieldtype":"Float","required":true,"in_list_view":true},{"fieldname":"serial_no","label":"Serial No","fieldtype":"Link","options":"Serial No","in_list_view":true},{"fieldname":"batch_no","label":"Batch","fieldtype":"Link","options":"Batch","in_list_view":true}],"permissions":[],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Repost Item Valuation','Stock',0,1,0,1,'{"name":"Repost Item Valuation","module":"Stock","is_submittable":true,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","required":true,"in_list_view":true},{"fieldname":"warehouse","label":"Warehouse","fieldtype":"Link","options":"Warehouse","required":true,"in_list_view":true},{"fieldname":"posting_at","label":"Posting At","fieldtype":"Datetime","required":true,"in_list_view":true},{"fieldname":"stock_account","label":"Stock Account","fieldtype":"Link","options":"Account","required":true},{"fieldname":"difference_account","label":"Difference Account","fieldtype":"Link","options":"Account","required":true},{"fieldname":"valuation_method","label":"Valuation Method","fieldtype":"Data","read_only":true},{"fieldname":"adjustment_minor","label":"Adjustment Minor","fieldtype":"Int","read_only":true}],"permissions":[{"role":"Stock Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Stock User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"REPOST-.YYYY.-#####","sort_field":"posting_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Return Item','Stock',0,0,1,1,'{"name":"Return Item","module":"Stock","is_submittable":false,"is_child":true,"track_changes":false,"revision":1,"fields":[{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","required":true,"in_list_view":true},{"fieldname":"qty","label":"Qty","fieldtype":"Float","required":true,"in_list_view":true},{"fieldname":"rate","label":"Rate","fieldtype":"Currency","required":true},{"fieldname":"warehouse","label":"Warehouse","fieldtype":"Link","options":"Warehouse"},{"fieldname":"income_account","label":"Income Account","fieldtype":"Link","options":"Account"},{"fieldname":"expense_account","label":"Expense Account","fieldtype":"Link","options":"Account"},{"fieldname":"serial_and_batch_bundle","label":"Serial/Batch Bundle","fieldtype":"Link","options":"Serial and Batch Bundle"}],"permissions":[],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Credit Note','Accounts',0,1,0,1,'{"name":"Credit Note","module":"Accounts","is_submittable":true,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"customer","label":"Customer","fieldtype":"Link","options":"Customer","required":true,"in_list_view":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"currency","label":"Currency","fieldtype":"Link","options":"Currency","required":true},{"fieldname":"posting_at","label":"Posting At","fieldtype":"Datetime","required":true,"in_list_view":true},{"fieldname":"return_against","label":"Sales Invoice","fieldtype":"Link","options":"Sales Invoice","required":true,"in_list_view":true,"search_index":true},{"fieldname":"debit_to","label":"Receivable Account","fieldtype":"Link","options":"Account","required":true},{"fieldname":"default_income_account","label":"Income Account","fieldtype":"Link","options":"Account","required":true},{"fieldname":"items","label":"Items","fieldtype":"Table","options":"Return Item","required":true},{"fieldname":"taxes","label":"Taxes","fieldtype":"Table","options":"Sales Taxes and Charges"},{"fieldname":"grand_total","label":"Grand Total","fieldtype":"Currency","read_only":true,"in_list_view":true}],"permissions":[{"role":"Accounts Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Accounts User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"CRN-.YYYY.-#####","title_field":"customer","search_fields":["customer","return_against"],"sort_field":"posting_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Debit Note','Accounts',0,1,0,1,'{"name":"Debit Note","module":"Accounts","is_submittable":true,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"supplier","label":"Supplier","fieldtype":"Link","options":"Supplier","required":true,"in_list_view":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"currency","label":"Currency","fieldtype":"Link","options":"Currency","required":true},{"fieldname":"posting_at","label":"Posting At","fieldtype":"Datetime","required":true,"in_list_view":true},{"fieldname":"return_against","label":"Purchase Invoice","fieldtype":"Link","options":"Purchase Invoice","required":true,"in_list_view":true,"search_index":true},{"fieldname":"credit_to","label":"Payable Account","fieldtype":"Link","options":"Account","required":true},{"fieldname":"default_expense_account","label":"Expense Account","fieldtype":"Link","options":"Account","required":true},{"fieldname":"items","label":"Items","fieldtype":"Table","options":"Return Item","required":true},{"fieldname":"taxes","label":"Taxes","fieldtype":"Table","options":"Purchase Taxes and Charges"},{"fieldname":"grand_total","label":"Grand Total","fieldtype":"Currency","read_only":true,"in_list_view":true}],"permissions":[{"role":"Accounts Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Accounts User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"DBN-.YYYY.-#####","title_field":"supplier","search_fields":["supplier","return_against"],"sort_field":"posting_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Stock Return','Stock',0,1,0,1,'{"name":"Stock Return","module":"Stock","is_submittable":true,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"return_type","label":"Return Type","fieldtype":"Select","options":"Sales\nPurchase","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"party","label":"Party","fieldtype":"Data","required":true,"in_list_view":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"currency","label":"Currency","fieldtype":"Link","options":"Currency","required":true},{"fieldname":"posting_at","label":"Posting At","fieldtype":"Datetime","required":true,"in_list_view":true},{"fieldname":"return_against","label":"Source Document","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"stock_account","label":"Stock Account","fieldtype":"Link","options":"Account"},{"fieldname":"cogs_or_expense_account","label":"COGS/Expense Account","fieldtype":"Link","options":"Account"},{"fieldname":"items","label":"Items","fieldtype":"Table","options":"Return Item","required":true}],"permissions":[{"role":"Stock Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Stock User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"SRET-.YYYY.-#####","search_fields":["party","return_against"],"sort_field":"posting_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Bill of Materials','Manufacturing',0,1,0,1,'{"name":"Bill of Materials","module":"Manufacturing","is_submittable":true,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"item","label":"Finished Item","fieldtype":"Link","options":"Item","required":true,"in_list_view":true,"search_index":true},{"fieldname":"quantity","label":"Quantity","fieldtype":"Float","required":true,"in_list_view":true},{"fieldname":"operating_cost","label":"Operating Cost","fieldtype":"Currency"},{"fieldname":"items","label":"Raw Materials","fieldtype":"Table","options":"BOM Item","required":true},{"fieldname":"raw_material_cost_minor","label":"Raw Material Cost Minor","fieldtype":"Int","read_only":true},{"fieldname":"total_cost_minor","label":"Total Cost Minor","fieldtype":"Int","read_only":true}],"permissions":[{"role":"Manufacturing Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Manufacturing User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"BOM-.#####","title_field":"item","search_fields":["item"],"sort_field":"modified_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','BOM Item','Manufacturing',0,0,1,1,'{"name":"BOM Item","module":"Manufacturing","is_submittable":false,"is_child":true,"track_changes":false,"revision":1,"fields":[{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","required":true,"in_list_view":true},{"fieldname":"qty","label":"Qty","fieldtype":"Float","required":true,"in_list_view":true},{"fieldname":"rate","label":"Rate","fieldtype":"Currency","read_only":true},{"fieldname":"source_warehouse","label":"Source Warehouse","fieldtype":"Link","options":"Warehouse"}],"permissions":[],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Work Order','Manufacturing',0,1,0,1,'{"name":"Work Order","module":"Manufacturing","is_submittable":true,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"production_item","label":"Production Item","fieldtype":"Link","options":"Item","required":true,"in_list_view":true,"search_index":true},{"fieldname":"bom_no","label":"BOM","fieldtype":"Link","options":"Bill of Materials","required":true,"in_list_view":true},{"fieldname":"qty","label":"Qty To Manufacture","fieldtype":"Float","required":true,"in_list_view":true},{"fieldname":"source_warehouse","label":"Source Warehouse","fieldtype":"Link","options":"Warehouse","required":true},{"fieldname":"wip_warehouse","label":"WIP Warehouse","fieldtype":"Link","options":"Warehouse"},{"fieldname":"target_warehouse","label":"Target Warehouse","fieldtype":"Link","options":"Warehouse","required":true},{"fieldname":"planned_start_date","label":"Planned Start","fieldtype":"Datetime"},{"fieldname":"planned_end_date","label":"Planned End","fieldtype":"Datetime"},{"fieldname":"required_items","label":"Required Items","fieldtype":"Table","options":"Work Order Required Item","read_only":true},{"fieldname":"produced_qty","label":"Produced Qty","fieldtype":"Float","read_only":true,"in_list_view":true},{"fieldname":"produced_percentage","label":"Produced %","fieldtype":"Percent","read_only":true,"in_list_view":true}],"permissions":[{"role":"Manufacturing Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Manufacturing User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"WO-.YYYY.-#####","title_field":"production_item","search_fields":["production_item","bom_no"],"sort_field":"modified_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Work Order Required Item','Manufacturing',0,0,1,1,'{"name":"Work Order Required Item","module":"Manufacturing","is_submittable":false,"is_child":true,"track_changes":false,"revision":1,"fields":[{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","required":true,"in_list_view":true},{"fieldname":"required_qty","label":"Required Qty","fieldtype":"Float","required":true,"in_list_view":true},{"fieldname":"source_warehouse","label":"Source Warehouse","fieldtype":"Link","options":"Warehouse","required":true}],"permissions":[],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Asset','Assets',0,1,0,1,'{"name":"Asset","module":"Assets","is_submittable":true,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"asset_name","label":"Asset Name","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"asset_category","label":"Asset Category","fieldtype":"Link","options":"Asset Category","required":true,"in_list_view":true},{"fieldname":"purchase_date","label":"Purchase Date","fieldtype":"Date","required":true},{"fieldname":"available_for_use_date","label":"Available For Use","fieldtype":"Date","required":true,"in_list_view":true},{"fieldname":"gross_purchase_amount","label":"Gross Purchase Amount","fieldtype":"Currency","required":true},{"fieldname":"salvage_value","label":"Salvage Value","fieldtype":"Currency","default":"0"},{"fieldname":"depreciation_method","label":"Depreciation Method","fieldtype":"Select","options":"Straight Line\nWritten Down Value\nDouble Declining Balance\nManual","required":true},{"fieldname":"total_number_of_depreciations","label":"Number of Depreciations","fieldtype":"Int","required":true},{"fieldname":"frequency_of_depreciation_months","label":"Frequency (Months)","fieldtype":"Int","required":true},{"fieldname":"depreciation_rate","label":"Depreciation Rate","fieldtype":"Percent"},{"fieldname":"fixed_asset_account","label":"Fixed Asset Account","fieldtype":"Link","options":"Account","required":true},{"fieldname":"accumulated_depreciation_account","label":"Accumulated Depreciation Account","fieldtype":"Link","options":"Account","required":true},{"fieldname":"depreciation_expense_account","label":"Depreciation Expense Account","fieldtype":"Link","options":"Account","required":true},{"fieldname":"accumulated_depreciation","label":"Accumulated Depreciation","fieldtype":"Currency","read_only":true},{"fieldname":"net_book_value","label":"Net Book Value","fieldtype":"Currency","read_only":true,"in_list_view":true}],"permissions":[{"role":"Asset Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Asset User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"ACC-ASSET-.YYYY.-#####","title_field":"asset_name","search_fields":["asset_name"],"sort_field":"modified_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Asset Depreciation Entry','Assets',0,1,0,1,'{"name":"Asset Depreciation Entry","module":"Assets","is_submittable":true,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"asset","label":"Asset","fieldtype":"Link","options":"Asset","required":true,"in_list_view":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"posting_at","label":"Posting At","fieldtype":"Datetime","required":true,"in_list_view":true},{"fieldname":"amount","label":"Amount","fieldtype":"Currency"},{"fieldname":"schedule_index","label":"Schedule Index","fieldtype":"Int"}],"permissions":[{"role":"Asset Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Asset User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"DEP-.YYYY.-#####","search_fields":["asset"],"sort_field":"posting_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Item Price','Selling',0,0,0,1,'{"name":"Item Price","module":"Selling","is_submittable":false,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"price_list","label":"Price List","fieldtype":"Data","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","required":true,"in_list_view":true,"search_index":true},{"fieldname":"currency","label":"Currency","fieldtype":"Link","options":"Currency","required":true},{"fieldname":"rate","label":"Rate","fieldtype":"Currency","required":true,"in_list_view":true},{"fieldname":"valid_from","label":"Valid From","fieldtype":"Date"},{"fieldname":"valid_upto","label":"Valid Upto","fieldtype":"Date"}],"permissions":[{"role":"Sales Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Sales User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"field:price_list","title_field":"item_code","search_fields":["item_code","price_list"],"sort_field":"modified_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Pricing Rule','Selling',0,0,0,1,'{"name":"Pricing Rule","module":"Selling","is_submittable":false,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"price_list","label":"Price List","fieldtype":"Data","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","in_list_view":true},{"fieldname":"party_type","label":"Party Type","fieldtype":"Select","options":"Customer\nSupplier"},{"fieldname":"party","label":"Party","fieldtype":"Data"},{"fieldname":"customer_group","label":"Customer Group","fieldtype":"Data"},{"fieldname":"supplier_group","label":"Supplier Group","fieldtype":"Data"},{"fieldname":"min_qty","label":"Minimum Qty","fieldtype":"Float"},{"fieldname":"max_qty","label":"Maximum Qty","fieldtype":"Float"},{"fieldname":"rate","label":"Rate","fieldtype":"Currency"},{"fieldname":"discount_percentage","label":"Discount %","fieldtype":"Percent"},{"fieldname":"priority","label":"Priority","fieldtype":"Int","default":0},{"fieldname":"valid_from","label":"Valid From","fieldtype":"Date"},{"fieldname":"valid_upto","label":"Valid Upto","fieldtype":"Date"},{"fieldname":"disabled","label":"Disabled","fieldtype":"Check","default":0}],"permissions":[{"role":"Sales Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Sales User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"PRULE-.#####","search_fields":["item_code","party"],"sort_field":"modified_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Batch','Stock',0,0,0,1,'{"name":"Batch","module":"Stock","is_submittable":false,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"batch_id","label":"Batch ID","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"item","label":"Item","fieldtype":"Link","options":"Item","required":true,"in_list_view":true},{"fieldname":"manufacturing_date","label":"Manufacturing Date","fieldtype":"Date"},{"fieldname":"expiry_date","label":"Expiry Date","fieldtype":"Date","in_list_view":true},{"fieldname":"disabled","label":"Disabled","fieldtype":"Check","default":0}],"permissions":[{"role":"Stock Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Stock User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"field:batch_id","title_field":"batch_id","search_fields":["batch_id","item"],"sort_field":"modified_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Serial No','Stock',0,0,0,1,'{"name":"Serial No","module":"Stock","is_submittable":false,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"serial_no","label":"Serial No","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","required":true,"in_list_view":true},{"fieldname":"warehouse","label":"Warehouse","fieldtype":"Link","options":"Warehouse","in_list_view":true},{"fieldname":"status","label":"Status","fieldtype":"Select","options":"Active\nDelivered\nInactive","default":"Active","in_list_view":true},{"fieldname":"warranty_expiry_date","label":"Warranty Expiry","fieldtype":"Date"}],"permissions":[{"role":"Stock Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Stock User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"field:serial_no","title_field":"serial_no","search_fields":["serial_no","item_code"],"sort_field":"modified_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Asset Category','Assets',0,0,0,1,'{"name":"Asset Category","module":"Assets","is_submittable":false,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"asset_category_name","label":"Asset Category","fieldtype":"Data","required":true,"in_list_view":true},{"fieldname":"fixed_asset_account","label":"Fixed Asset Account","fieldtype":"Link","options":"Account"},{"fieldname":"accumulated_depreciation_account","label":"Accumulated Depreciation","fieldtype":"Link","options":"Account"},{"fieldname":"depreciation_expense_account","label":"Depreciation Expense","fieldtype":"Link","options":"Account"}],"permissions":[{"role":"Asset Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Asset User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"field:asset_category_name","title_field":"asset_category_name","sort_field":"modified_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Project','Projects',0,0,0,1,'{"name":"Project","module":"Projects","is_submittable":false,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"project_name","label":"Project Name","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"status","label":"Status","fieldtype":"Select","options":"Open\nCompleted\nCancelled","default":"Open","in_list_view":true,"in_standard_filter":true},{"fieldname":"customer","label":"Customer","fieldtype":"Link","options":"Customer"},{"fieldname":"expected_start_date","label":"Expected Start","fieldtype":"Date"},{"fieldname":"expected_end_date","label":"Expected End","fieldtype":"Date"},{"fieldname":"percent_complete","label":"Percent Complete","fieldtype":"Percent","default":"0","in_list_view":true}],"permissions":[{"role":"Projects Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Projects User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"PROJ-.YYYY.-#####","title_field":"project_name","search_fields":["project_name"],"sort_field":"modified_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Task','Projects',0,0,0,1,'{"name":"Task","module":"Projects","is_submittable":false,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"subject","label":"Subject","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"project","label":"Project","fieldtype":"Link","options":"Project","in_list_view":true,"in_standard_filter":true},{"fieldname":"status","label":"Status","fieldtype":"Select","options":"Open\nWorking\nPending Review\nCompleted\nCancelled","default":"Open","in_list_view":true,"in_standard_filter":true},{"fieldname":"priority","label":"Priority","fieldtype":"Select","options":"Low\nMedium\nHigh\nUrgent","default":"Medium","in_list_view":true},{"fieldname":"exp_start_date","label":"Expected Start","fieldtype":"Date"},{"fieldname":"exp_end_date","label":"Expected End","fieldtype":"Date"},{"fieldname":"description","label":"Description","fieldtype":"Text Editor"}],"permissions":[{"role":"Projects Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Projects User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"TASK-.YYYY.-#####","title_field":"subject","search_fields":["subject"],"sort_field":"modified_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Timesheet','Projects',0,1,0,1,'{"name":"Timesheet","module":"Projects","is_submittable":true,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"employee","label":"Employee","fieldtype":"Data","in_list_view":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"start_date","label":"Start Date","fieldtype":"Date","required":true,"in_list_view":true},{"fieldname":"end_date","label":"End Date","fieldtype":"Date","required":true,"in_list_view":true},{"fieldname":"time_logs","label":"Time Logs","fieldtype":"Table","options":"Timesheet Detail","required":true},{"fieldname":"total_hours","label":"Total Hours","fieldtype":"Float","read_only":true,"in_list_view":true}],"permissions":[{"role":"Projects Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Projects User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"TS-.YYYY.-#####","sort_field":"start_date","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Timesheet Detail','Projects',0,0,1,1,'{"name":"Timesheet Detail","module":"Projects","is_submittable":false,"is_child":true,"track_changes":false,"revision":1,"fields":[{"fieldname":"activity_type","label":"Activity Type","fieldtype":"Data","required":true,"in_list_view":true},{"fieldname":"project","label":"Project","fieldtype":"Link","options":"Project"},{"fieldname":"task","label":"Task","fieldtype":"Link","options":"Task"},{"fieldname":"from_time","label":"From Time","fieldtype":"Datetime","required":true},{"fieldname":"to_time","label":"To Time","fieldtype":"Datetime","required":true},{"fieldname":"hours","label":"Hours","fieldtype":"Float","read_only":true,"in_list_view":true}],"permissions":[],"custom":false}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Quality Inspection','Quality',0,1,0,1,'{"name":"Quality Inspection","module":"Quality","is_submittable":true,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"inspection_type","label":"Inspection Type","fieldtype":"Select","options":"Incoming\nOutgoing\nIn Process","required":true,"in_list_view":true},{"fieldname":"reference_type","label":"Reference Type","fieldtype":"Data","in_list_view":true},{"fieldname":"reference_name","label":"Reference Name","fieldtype":"Data","in_list_view":true,"search_index":true},{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","required":true,"in_list_view":true},{"fieldname":"status","label":"Status","fieldtype":"Select","options":"Accepted\nRejected","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"remarks","label":"Remarks","fieldtype":"Small Text"}],"permissions":[{"role":"Quality Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Quality User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"QI-.YYYY.-#####","search_fields":["reference_name","item_code"],"sort_field":"modified_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','Issue','Support',0,0,0,1,'{"name":"Issue","module":"Support","is_submittable":false,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"subject","label":"Subject","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"customer","label":"Customer","fieldtype":"Link","options":"Customer","in_list_view":true},{"fieldname":"status","label":"Status","fieldtype":"Select","options":"Open\nReplied\nOn Hold\nResolved\nClosed","default":"Open","in_list_view":true,"in_standard_filter":true},{"fieldname":"priority","label":"Priority","fieldtype":"Select","options":"Low\nMedium\nHigh","default":"Medium","in_list_view":true},{"fieldname":"description","label":"Description","fieldtype":"Text Editor"},{"fieldname":"resolution_details","label":"Resolution","fieldtype":"Text Editor"}],"permissions":[{"role":"Support Team","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"ISS-.YYYY.-#####","title_field":"subject","search_fields":["subject"],"sort_field":"modified_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
INSERT OR REPLACE INTO doctype_definitions(tenant_id,doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at) VALUES('demo','POS Profile','Selling',0,0,0,1,'{"name":"POS Profile","module":"Selling","is_submittable":false,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"profile_name","label":"Profile Name","fieldtype":"Data","required":true,"in_list_view":true,"search_index":true},{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"warehouse","label":"Warehouse","fieldtype":"Link","options":"Warehouse","required":true},{"fieldname":"currency","label":"Currency","fieldtype":"Link","options":"Currency","required":true},{"fieldname":"selling_price_list","label":"Selling Price List","fieldtype":"Data","required":true},{"fieldname":"income_account","label":"Income Account","fieldtype":"Link","options":"Account","required":true},{"fieldname":"cash_account","label":"Cash Account","fieldtype":"Link","options":"Account","required":true},{"fieldname":"disabled","label":"Disabled","fieldtype":"Check","default":0}],"permissions":[{"role":"Sales Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Sales User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"field:profile_name","title_field":"profile_name","search_fields":["profile_name"],"sort_field":"modified_at","sort_order":"DESC"}',0,'migration','2026-07-25T00:00:00.000Z');
UPDATE doctype_definitions SET revision=2,metadata_json='{"name":"Stock Entry","module":"Stock","is_submittable":true,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"company","label":"Company","fieldtype":"Link","options":"Company","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"posting_at","label":"Posting At","fieldtype":"Datetime","required":true,"in_list_view":true},{"fieldname":"purpose","label":"Purpose","fieldtype":"Select","options":"Material Receipt\nMaterial Issue\nMaterial Transfer\nManufacture","required":true,"in_list_view":true,"in_standard_filter":true},{"fieldname":"work_order","label":"Work Order","fieldtype":"Link","options":"Work Order"},{"fieldname":"source_warehouse","label":"Source Warehouse","fieldtype":"Link","options":"Warehouse"},{"fieldname":"target_warehouse","label":"Target Warehouse","fieldtype":"Link","options":"Warehouse"},{"fieldname":"finished_good_item","label":"Finished Good","fieldtype":"Link","options":"Item"},{"fieldname":"finished_good_qty","label":"Finished Qty","fieldtype":"Float"},{"fieldname":"finished_good_bundle","label":"Finished Serial/Batch Bundle","fieldtype":"Link","options":"Serial and Batch Bundle"},{"fieldname":"items","label":"Items","fieldtype":"Table","options":"Stock Entry Detail","required":true}],"permissions":[{"role":"Stock Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true},{"role":"Stock User","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":false,"cancel":false},{"role":"System Manager","read":true,"write":true,"create":true,"print":true,"email":true,"report":true,"import":true,"export":true,"share":true,"submit":true,"cancel":true}],"custom":false,"autoname":"STE-.YYYY.-#####","sort_field":"posting_at","sort_order":"DESC"}',modified_by='migration',modified_at='2026-07-25T00:00:00.000Z' WHERE tenant_id='demo' AND doctype='Stock Entry';
UPDATE doctype_definitions SET revision=2,metadata_json='{"name":"Stock Entry Detail","module":"Stock","is_submittable":false,"is_child":true,"track_changes":false,"revision":1,"fields":[{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","required":true,"in_list_view":true},{"fieldname":"qty","label":"Qty","fieldtype":"Float","required":true,"in_list_view":true},{"fieldname":"source_warehouse","label":"Source Warehouse","fieldtype":"Link","options":"Warehouse"},{"fieldname":"target_warehouse","label":"Target Warehouse","fieldtype":"Link","options":"Warehouse"},{"fieldname":"valuation_rate","label":"Valuation Rate","fieldtype":"Currency"},{"fieldname":"serial_and_batch_bundle","label":"Serial/Batch Bundle","fieldtype":"Link","options":"Serial and Batch Bundle"}],"permissions":[],"custom":false}',modified_by='migration',modified_at='2026-07-25T00:00:00.000Z' WHERE tenant_id='demo' AND doctype='Stock Entry Detail';
DELETE FROM doctype_definitions WHERE tenant_id='__standard__' AND doctype IN ('Serial and Batch Bundle','Serial and Batch Bundle Entry','Repost Item Valuation','Return Item','Credit Note','Debit Note','Stock Return','Bill of Materials','BOM Item','Work Order','Work Order Required Item','Asset','Asset Depreciation Entry','Item Price','Pricing Rule','Batch','Serial No','Asset Category','Project','Task','Timesheet','Timesheet Detail','Quality Inspection','Issue','POS Profile','Stock Entry','Stock Entry Detail');
INSERT INTO doctype_definitions SELECT '__standard__',doctype,module,is_custom,is_submittable,is_child,revision,metadata_json,disabled,modified_by,modified_at FROM doctype_definitions WHERE tenant_id='demo' AND doctype IN ('Serial and Batch Bundle','Serial and Batch Bundle Entry','Repost Item Valuation','Return Item','Credit Note','Debit Note','Stock Return','Bill of Materials','BOM Item','Work Order','Work Order Required Item','Asset','Asset Depreciation Entry','Item Price','Pricing Rule','Batch','Serial No','Asset Category','Project','Task','Timesheet','Timesheet Detail','Quality Inspection','Issue','POS Profile','Stock Entry','Stock Entry Detail');
-- END ERPNext Core standard metadata v0.8
