-- Reusable Alumdoor BOM Rule authority.
--
-- Cutting Policy remains the parent-door geometry authority. BOM Rule only describes how a
-- component consumes that geometry. The master is reusable by many BOMs/templates and keeps
-- source provenance separate from the effective owner-confirmed formula.

INSERT OR REPLACE INTO doctype_definitions(
  tenant_id, doctype, module, is_custom, is_submittable, is_child, revision,
  metadata_json, disabled, modified_by, modified_at
)
SELECT DISTINCT
  tenant_id,
  'BOM Rule',
  'Manufacturing',
  0, 0, 0, 1,
  json('{"name":"BOM Rule","module":"Manufacturing","autoname":"field:rule_code","title_field":"rule_name","search_fields":"rule_code,rule_name,description,source_formula_text","is_submittable":false,"is_child":false,"track_changes":true,"revision":1,"fields":[{"fieldname":"rule_code","label":"Mã quy tắc","fieldtype":"Data","required":true,"unique":true,"in_list_view":true},{"fieldname":"rule_name","label":"Tên quy tắc","fieldtype":"Data","required":true,"in_list_view":true},{"fieldname":"description","label":"Mô tả","fieldtype":"Small Text"},{"fieldname":"result_kind","label":"Loại kết quả","fieldtype":"Select","options":"LENGTH\nAREA\nCOUNT\nWEIGHT\nCONSTANT","required":true,"in_list_view":true},{"fieldname":"result_uom","label":"ĐVT kết quả / tiêu hao","fieldtype":"Link","options":"UOM","required":true,"in_list_view":true},{"fieldname":"source_field","label":"Trường nguồn từ hàng cha","fieldtype":"Link","options":"Geometry Field"},{"fieldname":"operator","label":"Phép tính","fieldtype":"Select","options":"COPY\nADD\nSUBTRACT\nMULTIPLY\nDIVIDE\nCONSTANT","default":"COPY","required":true},{"fieldname":"operand","label":"Giá trị cộng / trừ / nhân / chia","fieldtype":"Float","default":0},{"fieldname":"multiply","label":"Hệ số nhân","fieldtype":"Float","default":1},{"fieldname":"divide","label":"Hệ số chia","fieldtype":"Float","default":1},{"fieldname":"qty_per_set","label":"Số lượng mỗi bộ","fieldtype":"Float","default":1,"required":true},{"fieldname":"rounding","label":"Làm tròn","fieldtype":"Select","options":"NONE\nROUND\nCEIL\nFLOOR","default":"NONE"},{"fieldname":"precision","label":"Số chữ số","fieldtype":"Int","default":6},{"fieldname":"formula_json","label":"Công thức canonical JSON","fieldtype":"Long Text","read_only":true},{"fieldname":"formula_display","label":"Công thức hiển thị","fieldtype":"Data","read_only":true,"in_list_view":true},{"fieldname":"version","label":"Phiên bản","fieldtype":"Int","default":1,"required":true,"in_list_view":true},{"fieldname":"disabled","label":"Ngưng dùng","fieldtype":"Check","default":0,"in_list_view":true},{"fieldname":"applicability","label":"Áp dụng cho","fieldtype":"Table","options":"BOM Rule Applicability"},{"fieldname":"authority_type","label":"Nguồn thẩm quyền","fieldtype":"Select","options":"SOURCE\nOWNER_CONFIRMED\nENGINEERING_INFERENCE","default":"SOURCE","required":true},{"fieldname":"source_sheet","label":"Sheet nguồn","fieldtype":"Data"},{"fieldname":"source_row","label":"Dòng nguồn","fieldtype":"Int"},{"fieldname":"source_formula_text","label":"Công thức nguồn gốc","fieldtype":"Small Text"},{"fieldname":"source_formula_code","label":"Mã công thức nguồn","fieldtype":"Data"},{"fieldname":"source_note","label":"Ghi chú nguồn / xác nhận","fieldtype":"Small Text"},{"fieldname":"confirmed_by","label":"Người xác nhận","fieldtype":"Data"},{"fieldname":"confirmed_at","label":"Thời điểm xác nhận","fieldtype":"Datetime"}],"permissions":[],"custom":false}'),
  0, 'migration-0134', '2026-08-19T05:50:00.000Z'
FROM doctype_definitions
WHERE doctype IN ('BOM Template', 'Bill of Materials');

INSERT OR REPLACE INTO doctype_definitions(
  tenant_id, doctype, module, is_custom, is_submittable, is_child, revision,
  metadata_json, disabled, modified_by, modified_at
)
SELECT DISTINCT
  tenant_id,
  'BOM Rule Applicability',
  'Manufacturing',
  0, 0, 1, 1,
  json('{"name":"BOM Rule Applicability","module":"Manufacturing","is_submittable":false,"is_child":true,"track_changes":false,"revision":1,"fields":[{"fieldname":"scope_type","label":"Phạm vi","fieldtype":"Select","options":"BOM\nITEM\nITEM_GROUP\nDOOR_TYPE\nGENERIC","default":"ITEM","required":true,"in_list_view":true},{"fieldname":"parent_item","label":"Mặt hàng cha","fieldtype":"Link","options":"Item","in_list_view":true},{"fieldname":"parent_item_group","label":"Nhóm hàng cha","fieldtype":"Link","options":"Item Group","in_list_view":true},{"fieldname":"door_type","label":"Loại cửa","fieldtype":"Select","options":"Cửa Đức\nCửa Úc\nCửa Lưới\nCửa Đài Loan\nCửa Siêu Trường\nCửa tấm liền Úc","in_list_view":true},{"fieldname":"component_item","label":"Thành phần con","fieldtype":"Link","options":"Item","required":true,"in_list_view":true},{"fieldname":"bom","label":"BOM","fieldtype":"Link","options":"Bill of Materials"},{"fieldname":"priority","label":"Ưu tiên","fieldtype":"Int","default":0},{"fieldname":"effective_from","label":"Hiệu lực từ","fieldtype":"Date"},{"fieldname":"effective_to","label":"Hiệu lực đến","fieldtype":"Date"},{"fieldname":"disabled","label":"Ngưng dùng","fieldtype":"Check","default":0},{"fieldname":"note","label":"Ghi chú","fieldtype":"Data"}],"permissions":[],"custom":false}'),
  0, 'migration-0134', '2026-08-19T05:50:00.000Z'
FROM doctype_definitions
WHERE doctype IN ('BOM Template', 'Bill of Materials');

-- Existing template child keeps its source snapshot but can now link to the reusable master.
UPDATE doctype_definitions
SET revision = 2,
    metadata_json = json('{"name":"BOM Component Rule","module":"Manufacturing","is_submittable":false,"is_child":true,"track_changes":false,"revision":2,"fields":[{"fieldname":"rule_code","label":"Mã dòng quy tắc","fieldtype":"Data","required":true,"in_list_view":true},{"fieldname":"component_key","label":"Khóa thành phần","fieldtype":"Data"},{"fieldname":"item_code","label":"Vật tư","fieldtype":"Link","options":"Item","required":true,"in_list_view":true},{"fieldname":"bom_rule","label":"Quy tắc BOM dùng chung","fieldtype":"Link","options":"BOM Rule","in_list_view":true},{"fieldname":"bom_rule_version","label":"Phiên bản quy tắc","fieldtype":"Int","read_only":true},{"fieldname":"stock_uom","label":"Đơn vị tồn","fieldtype":"Link","options":"UOM"},{"fieldname":"conditions_json","label":"Điều kiện JSON","fieldtype":"Code"},{"fieldname":"priority","label":"Ưu tiên","fieldtype":"Int","default":0},{"fieldname":"sequence","label":"Thứ tự","fieldtype":"Int","default":0},{"fieldname":"quantity_formula_json","label":"Công thức cũ / fallback","fieldtype":"Code"},{"fieldname":"bom_rule_formula_snapshot","label":"Snapshot công thức BOM Rule","fieldtype":"Long Text","read_only":true},{"fieldname":"source_row","label":"Dòng nguồn","fieldtype":"Int"},{"fieldname":"source_uom","label":"ĐVT nguồn","fieldtype":"Data"},{"fieldname":"source_formula","label":"Công thức nguồn","fieldtype":"Small Text"},{"fieldname":"note","label":"Ghi chú","fieldtype":"Small Text"}],"permissions":[],"custom":false}'),
    modified_by = 'migration-0134',
    modified_at = '2026-08-19T05:50:00.000Z'
WHERE doctype = 'BOM Component Rule';

-- BOM Item keeps lineage and now records the reusable rule/snapshot used to calculate the row.
UPDATE doctype_definitions
SET revision = 3,
    metadata_json = json('{"name":"BOM Item","module":"Manufacturing","is_submittable":false,"is_child":true,"track_changes":false,"revision":3,"fields":[{"fieldname":"item_code","label":"Item","fieldtype":"Link","options":"Item","required":true,"in_list_view":true},{"fieldname":"qty","label":"Qty","fieldtype":"Float","required":false,"in_list_view":true},{"fieldname":"uom","label":"UOM","fieldtype":"Link","options":"UOM","in_list_view":true},{"fieldname":"stock_uom","label":"Stock UOM","fieldtype":"Link","options":"UOM","read_only":true},{"fieldname":"conversion_factor","label":"Conversion Factor","fieldtype":"Float"},{"fieldname":"qty_basis","label":"Qty Basis","fieldtype":"Data"},{"fieldname":"bom_rule","label":"Quy tắc BOM","fieldtype":"Link","options":"BOM Rule","in_list_view":true},{"fieldname":"bom_rule_version","label":"Phiên bản quy tắc","fieldtype":"Int","read_only":true},{"fieldname":"bom_rule_formula_snapshot","label":"Snapshot quy tắc BOM","fieldtype":"Long Text","read_only":true},{"fieldname":"consumption_qty","label":"SL tiêu hao","fieldtype":"Float","read_only":true},{"fieldname":"consumption_uom","label":"ĐVT tiêu hao","fieldtype":"Link","options":"UOM","read_only":true},{"fieldname":"quantity_formula_json","label":"Quantity Formula JSON","fieldtype":"Long Text"},{"fieldname":"bom_template_code","label":"BOM Template","fieldtype":"Data"},{"fieldname":"component_key","label":"Component Key","fieldtype":"Data"},{"fieldname":"source_value_status","label":"Source Value Status","fieldtype":"Select","options":"RESOLVED\nPENDING","in_list_view":true},{"fieldname":"source_pending_reason","label":"Pending Reason","fieldtype":"Data"},{"fieldname":"source_value","label":"Raw Source Value","fieldtype":"Data"},{"fieldname":"source_sequence","label":"Source Sequence","fieldtype":"Int"},{"fieldname":"source_sheet","label":"Source Sheet","fieldtype":"Data"},{"fieldname":"source_row","label":"Source Row","fieldtype":"Int"},{"fieldname":"source_index","label":"Source Index","fieldtype":"Int"},{"fieldname":"source_parent_row","label":"Source Parent Row","fieldtype":"Int"},{"fieldname":"source_item_code","label":"Raw Material Source Code","fieldtype":"Data"},{"fieldname":"source_item_name","label":"Raw Material Source Name","fieldtype":"Data"},{"fieldname":"source_uom","label":"Source UOM","fieldtype":"Data"},{"fieldname":"source_qty_or_formula","label":"Source Qty / Formula","fieldtype":"Data"},{"fieldname":"source_formula_code","label":"Source Formula Code","fieldtype":"Data"},{"fieldname":"source_formula_text","label":"Source Formula Text","fieldtype":"Long Text"},{"fieldname":"resolution_reason","label":"Resolution Reason","fieldtype":"Data"},{"fieldname":"rate","label":"Rate","fieldtype":"Currency","read_only":true},{"fieldname":"source_warehouse","label":"Source Warehouse","fieldtype":"Link","options":"Warehouse"}],"permissions":[],"custom":false}'),
    modified_by = 'migration-0134',
    modified_at = '2026-08-19T05:50:00.000Z'
WHERE doctype = 'BOM Item';
