import { closeSync, existsSync, mkdirSync, openSync, readFileSync, renameSync, unlinkSync, writeFileSync } from 'node:fs';
import crypto from 'node:crypto';
import os from 'node:os';
import path from 'node:path';
import process from 'node:process';
import { spawnSync } from 'node:child_process';
import { ExecutionError, classifyExistingLock, normalizeSpawnInvocation } from './run-local-import-core.mjs';

const ROOT='C:\\alumdoor', ORIGIN='http://127.0.0.1:8799';
const fail=(c,m,cause)=>new ExecutionError(c,m,cause?{cause}:{});
function run(cmd,args,{cwd,env,capture=false,label=cmd,failureClass='OTHER'}={}){const i=normalizeSpawnInvocation(cmd,args);const r=spawnSync(i.command,i.args,{cwd,env:{...process.env,...env},encoding:'utf8',windowsHide:true,stdio:capture?['ignore','pipe','pipe']:'inherit'});if(capture){if(r.stdout)process.stdout.write(r.stdout);if(r.stderr)process.stderr.write(r.stderr);}if(r.error)throw fail(failureClass,`${label} failed to start: ${r.error.message}`,r.error);if(r.status!==0)throw fail(failureClass,`${label} failed with exit code ${r.status}`);return r.stdout??'';}
const git=(root,args,capture=true)=>run('git',['-C',root,...args],{capture,label:`git ${args.join(' ')}`,failureClass:'CHECKOUT'}).trim();
function assertLoopback(origin){const u=new URL(origin);if(!['127.0.0.1','localhost','::1'].includes(u.hostname))throw fail('REMOTE_MUTATION_GUARD',`origin must be loopback, got ${u.hostname}`);}
async function api(origin){const c=new AbortController(),t=setTimeout(()=>c.abort(),5000);try{const r=await fetch(`${origin}/api/method/metaforge.api.get_boot`,{signal:c.signal});if(![200,401,403].includes(r.status))throw fail('ENV',`Local API unhealthy HTTP ${r.status}`);}finally{clearTimeout(t);}}
function repo(root){if(process.platform!=='win32'&&process.env.FORGE_LOCAL_RUNNER_ALLOW_NON_WINDOWS!=='1')throw fail('ENV',`Windows self-hosted runner required; got ${process.platform}`);if(Number(process.versions.node.split('.')[0])<22)throw fail('DEPENDENCY',`Node >=22 required; got ${process.version}`);if(!existsSync(path.join(root,'.git')))throw fail('PATH',`${root} is not a Git workspace`);if(git(root,['rev-parse','--abbrev-ref','HEAD'])!=='main')throw fail('STALE_WORKTREE','Local Customer authority must be main');const dirty=git(root,['status','--porcelain=v1']);if(dirty)throw fail('STALE_WORKTREE',`Local runtime dirty:\n${dirty}`);git(root,['fetch','origin','main','--prune'],false);const local=git(root,['rev-parse','HEAD']),remote=git(root,['rev-parse','origin/main']);if(local!==remote)throw fail('STALE_WORKTREE',`local=${local} origin/main=${remote}`);const expected=process.env.FORGE_LOCAL_EXPECTED_SHA?.trim();if(expected&&expected!==local)throw fail('STALE_WORKTREE',`expected=${expected} actual=${local}`);return local;}
function lock(root,runId,sha){const dir=path.join(root,'local-locks');mkdirSync(dir,{recursive:true});const p=path.join(dir,'local-d1-mutation.lock');const body={format:'forge-local-d1-lock/v2',run_id:runId,adapter:'customer',pid:process.pid,hostname:os.hostname(),started_at:new Date().toISOString(),workflow:process.env.GITHUB_WORKFLOW||'manual',github_run_id:process.env.GITHUB_RUN_ID||'',repo_sha:sha};for(let n=0;n<2;n++){try{const fd=openSync(p,'wx');try{writeFileSync(fd,`${JSON.stringify(body,null,2)}\n`);}finally{closeSync(fd);}console.log(`GLOBAL_D1_LOCK=ACQUIRED path=${p} run_id=${runId}`);return p;}catch(e){if(e?.code!=='EEXIST')throw fail('FILE_LOCK',e.message,e);let old;try{old=JSON.parse(readFileSync(p,'utf8'));}catch(pe){throw fail('FILE_LOCK','Existing lock unreadable',pe);}const verdict=classifyExistingLock(old);if(verdict.action!=='reap')throw fail('FILE_LOCK',`Lock ownership unproven: ${JSON.stringify({...old,verdict})}`);renameSync(p,`${p}.stale-${Date.now()}`);}}throw fail('FILE_LOCK','Cannot acquire global D1 lock');}
function unlock(p,runId){if(!p||!existsSync(p))return;const body=JSON.parse(readFileSync(p,'utf8'));if(body.run_id!==runId)throw fail('FILE_LOCK',`Refusing to release ${body.run_id}`);unlinkSync(p);console.log(`GLOBAL_D1_LOCK=RELEASED path=${p} run_id=${runId}`);}
function backup(root){const out=run(process.execPath,[path.join(root,'server','scripts','backup-local-state.mjs')],{cwd:root,capture:true,label:'backup-local-state',failureClass:'D1_STATE'});const m=out.match(/LOCAL_STATE_BACKUP_OK path=(.+) bytes=(\d+)/);if(!m||!existsSync(m[1].trim())||Number(m[2])<=0)throw fail('D1_STATE','Backup evidence invalid');console.log(`BACKUP_STATUS=PASS path=${m[1].trim()} bytes=${m[2]}`);return m[1].trim();}
function child(root,evidence,flags=[]){const env={FORGE_ORIGIN:process.env.FORGE_ORIGIN||ORIGIN,FORGE_ADMIN_USER:process.env.FORGE_ADMIN_USER||'dev@example.com',FORGE_ADMIN_PASSWORD:process.env.FORGE_ADMIN_PASSWORD||'local-dev-password-1'};run(process.execPath,[path.join(root,'server','scripts','import-alumdoor-customer-local.mjs'),evidence,...flags],{cwd:root,env,label:`Customer ${flags.join(' ')||'preflight'}`,failureClass:flags.includes('--apply')?'IMPORTER':'DATA'});return JSON.parse(readFileSync(evidence,'utf8'));}
export async function mainCustomer(){const root=path.win32.resolve(process.env.FORGE_LOCAL_REPO_ROOT||ROOT),origin=(process.env.FORGE_ORIGIN||ORIGIN).replace(/\/$/,'');const runId=`${new Date().toISOString().replace(/[:.]/g,'-')}-${crypto.randomBytes(4).toString('hex')}`;let lockPath='',stage='INFRA';try{console.log('INFRA_STATUS=RUNNING adapter=customer');assertLoopback(origin);const sha=repo(root);await api(origin);for(const f of ['data/customer-export.xlsx','data/don-hang-xuat-hang.xlsx','server/scripts/import-alumdoor-customer-local.mjs','server/scripts/backup-local-state.mjs'])if(!existsSync(path.join(root,f)))throw fail('SOURCE_FILE',`Missing ${f}`);console.log(`INFRA_STATUS=PASS sha=${sha} repo=${root}`);const dir=path.join(root,'local-backups','execution-layer','customer',runId);mkdirSync(dir,{recursive:true});stage='DATA';const pre=child(root,path.join(dir,'preflight.json'));if(Number(pre.preflight?.blocked??1)!==0)throw fail('DATA',`Customer blocked=${pre.preflight?.blocked}`);console.log(`DATA_STATUS=PASS canonical=${pre.canonical_rows} ready=${pre.preflight.ready}`);stage='LOCK';lockPath=lock(root,runId,sha);stage='BACKUP';const backupPath=backup(root);stage='IMPORT';const first=child(root,path.join(dir,'pass1.json'),['--apply']);if(Number(first.verify?.blocked??1)!==0)throw fail('VERIFY','Customer post-verify failed');stage='VERIFY';const second=child(root,path.join(dir,'pass2-idempotent.json'),['--apply','--expect-idempotent']);if(Number(second.commit?.imported??-1)!==0||Number(second.verify?.blocked??1)!==0)throw fail('VERIFY','Customer idempotency failed');writeFileSync(path.join(dir,'adapter-status.json'),`${JSON.stringify({adapter:'customer',run_id:runId,repo_sha:sha,backup_path:backupPath,canonical:first.canonical_rows,imported:first.commit.imported,idempotent_imported:second.commit.imported},null,2)}\n`);console.log(`ALUMDOOR_LOCAL_CUSTOMER_IMPORT_PASS canonical=${first.canonical_rows} imported_first=${first.commit.imported} imported_second=0`);console.log(`FORGE_LOCAL_IMPORT_EXECUTION_PASS adapter=customer run_id=${runId}`);console.log('EXECUTION_STATUS=SUCCESS');}catch(error){const e=error instanceof ExecutionError?error:fail('OTHER',error?.message??String(error),error);console.error(`EXECUTION_STATUS=FAILED adapter=customer stage=${stage} failure_class=${e.failureClass} message=${JSON.stringify(e.message)}`);throw e;}finally{if(lockPath)unlock(lockPath,runId);}}
