/** @jsxImportSource react */
import { Button } from "@metaforge/ui";
import { useMetaForge } from "../container/provider.js";
import type { ActionScreenProps } from "./ActionScreen.js";

type Row = Record<string, unknown>;
export interface SupplierDashboard extends Row {
  supplier: string;
  generated_at: string;
  source: "purchase_allocation_ledger" | "submitted_documents_fallback";
  summary: Row & {
    purchase_order_count: number; open_purchase_order_count: number; overdue_purchase_order_count: number;
    ordered_bars: number; received_bars: number; remaining_bars: number; ordered_meters: number; received_meters: number; remaining_meters: number;
    ordered_barem_weight_kg: number; received_barem_weight_kg: number; remaining_barem_weight_kg: number; actual_received_weight_kg: number; purchase_value: number;
  };
  materials: Row[]; purchase_orders: Row[]; purchase_order_lines: Row[]; receipts: Row[]; price_history: Row[];
  payable: Row & { authoritative: boolean; source: string; received_value: number; invoice_total: number; received_not_invoiced_hint: number; total_outstanding: number; overdue_amount: number | null; advance_balance: number | null; net_exposure: number; note: string };
}

const text = (value: unknown) => String(value ?? "").trim();
const num = (value: unknown) => { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : 0; };
function date(value: unknown): string { const raw = text(value); if (!raw) return "—"; const parsed = new Date(raw.length === 10 ? `${raw}T00:00:00` : raw.replace(" ", "T")); return Number.isNaN(parsed.getTime()) ? raw : parsed.toLocaleDateString("vi-VN"); }
function datetime(value: unknown): string { const raw = text(value); if (!raw) return "—"; const parsed = new Date(raw.replace(" ", "T")); return Number.isNaN(parsed.getTime()) ? raw : parsed.toLocaleString("vi-VN"); }
function statusClass(value: unknown): string { const status = text(value); if (/quá hạn|vượt|đảo/i.test(status)) return "text-destructive"; if (/đã giao đủ|đã đối soát/i.test(status)) return "text-emerald-700 dark:text-emerald-400"; if (/đang giao|còn phải giao/i.test(status)) return "text-amber-700 dark:text-amber-400"; return "text-muted-foreground"; }
function Empty({ children }: { children: string }) { return <div className="rounded-xl border border-dashed px-4 py-8 text-center text-sm text-muted-foreground">{children}</div>; }
function OpenDoc({ doctype, name, onOpen }: { doctype: string; name: string; onOpen?: ActionScreenProps["onOpen"] }) { return onOpen ? <Button variant="link" className="h-auto p-0 font-semibold" onClick={() => onOpen(doctype, name)}>{name}</Button> : <span className="font-semibold">{name}</span>; }
function Stack({ a, b, c, strong }: { a: string; b?: string; c?: string; strong?: boolean }) { return <div className={`tabular-nums ${strong ? "font-semibold" : ""}`}><div>{a}</div>{b ? <div className="text-[11px] text-muted-foreground">{b}</div> : null}{c ? <div className="text-[11px] text-muted-foreground">{c}</div> : null}</div>; }

export function DeliveryMaterialTable({ rows }: { rows: Row[] }) {
  const { fmt } = useMetaForge(); if (!rows.length) return <Empty>Chưa có nghĩa vụ giao hàng.</Empty>;
  return <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[1300px] text-sm"><thead className="bg-muted/50 text-left text-xs text-muted-foreground"><tr><th className="px-3 py-2.5">Quy cách</th><th className="px-3 py-2.5 text-right">Đặt</th><th className="px-3 py-2.5 text-right">Nhận</th><th className="px-3 py-2.5 text-right">Còn phải giao</th><th className="px-3 py-2.5 text-right">Kg thực / lệch</th><th className="px-3 py-2.5 text-right">Chưa phân bổ</th><th className="px-3 py-2.5 text-right">Dung sai</th><th className="px-3 py-2.5">PO mở cũ nhất</th><th className="px-3 py-2.5">Trạng thái</th></tr></thead><tbody>{rows.map((row, index) => <tr key={`${text(row.queue_key)}-${index}`} className="border-t align-top"><td className="px-3 py-2.5 font-medium">{text(row.material)}</td><td className="px-3 py-2.5 text-right"><Stack a={`${fmt.number(num(row.ordered_bars))} cây`} b={`${fmt.number(num(row.ordered_meters))} m`} c={`${fmt.number(num(row.ordered_barem_weight_kg))} kg barem`} /></td><td className="px-3 py-2.5 text-right"><Stack a={`${fmt.number(num(row.received_bars))} cây`} b={`${fmt.number(num(row.received_meters))} m`} c={`${fmt.number(num(row.received_barem_weight_kg))} kg barem`} /></td><td className="px-3 py-2.5 text-right"><Stack strong a={`${fmt.number(num(row.remaining_bars))} cây`} b={`${fmt.number(num(row.remaining_meters))} m`} c={`${fmt.number(num(row.remaining_barem_weight_kg))} kg barem`} /></td><td className="px-3 py-2.5 text-right"><Stack a={row.actual_weight_kg == null ? "—" : `${fmt.number(num(row.actual_weight_kg))} kg`} b={row.weight_variance_kg == null ? undefined : `${num(row.weight_variance_kg) > 0 ? "+" : ""}${fmt.number(num(row.weight_variance_kg))} kg`} c={row.weight_variance_pct == null ? undefined : `${num(row.weight_variance_pct) > 0 ? "+" : ""}${fmt.number(num(row.weight_variance_pct))}%`} /></td><td className="px-3 py-2.5 text-right">{fmt.number(num(row.unapplied_bars))} cây</td><td className="px-3 py-2.5 text-right">{text(row.tolerance) || "—"}</td><td className="px-3 py-2.5">{date(row.oldest_open_po_date)}{num(row.overdue_days) > 0 ? <div className="text-[11px] text-destructive">{fmt.number(num(row.overdue_days))} ngày</div> : null}</td><td className={`px-3 py-2.5 font-medium ${statusClass(row.status)}`}>{text(row.status)}</td></tr>)}</tbody></table></div>;
}

export function DeliveryOrderTable({ rows, onOpen }: { rows: Row[]; onOpen?: ActionScreenProps["onOpen"] }) {
  const { fmt } = useMetaForge(); const money = (value: number) => fmt.currency ? fmt.currency(value) : fmt.number(value); if (!rows.length) return <Empty>Chưa có đơn mua.</Empty>;
  return <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-muted/50 text-left text-xs text-muted-foreground"><tr><th className="px-3 py-2.5">PO</th><th className="px-3 py-2.5">Ngày</th><th className="px-3 py-2.5">Hẹn giao</th><th className="px-3 py-2.5 text-right">Đặt</th><th className="px-3 py-2.5 text-right">Nhận</th><th className="px-3 py-2.5 text-right">Còn</th><th className="px-3 py-2.5 text-right">Thiếu đã chốt</th><th className="px-3 py-2.5 text-right">% nhận</th><th className="px-3 py-2.5 text-right">% HĐ</th><th className="px-3 py-2.5 text-right">Giá trị</th><th className="px-3 py-2.5">Trạng thái</th></tr></thead><tbody>{rows.map((row) => <tr key={text(row.purchase_order)} className="border-t"><td className="px-3 py-2.5"><OpenDoc doctype="Purchase Order" name={text(row.purchase_order)} onOpen={onOpen} /></td><td className="px-3 py-2.5">{date(row.transaction_date)}</td><td className="px-3 py-2.5">{date(row.schedule_date)}</td><td className="px-3 py-2.5 text-right">{fmt.number(num(row.ordered_bars))}</td><td className="px-3 py-2.5 text-right">{fmt.number(num(row.received_bars))}</td><td className="px-3 py-2.5 text-right font-semibold">{fmt.number(num(row.remaining_bars))}</td><td className="px-3 py-2.5 text-right">{num(row.shortage_variance_bars) > 0 ? fmt.number(num(row.shortage_variance_bars)) : "—"}</td><td className="px-3 py-2.5 text-right">{fmt.number(num(row.received_percentage))}%</td><td className="px-3 py-2.5 text-right">{fmt.number(num(row.billed_percentage))}%</td><td className="px-3 py-2.5 text-right">{money(num(row.purchase_value))}</td><td className={`px-3 py-2.5 font-medium ${statusClass(row.status)}`}>{text(row.status)}</td></tr>)}</tbody></table></div>;
}

export function DeliveryOrderLineTable({ rows, onOpen }: { rows: Row[]; onOpen?: ActionScreenProps["onOpen"] }) {
  const { fmt } = useMetaForge(); if (!rows.length) return <Empty>Chưa có dòng PO để đối chiếu.</Empty>;
  return <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[1180px] text-sm"><thead className="bg-muted/50 text-left text-xs text-muted-foreground"><tr><th className="px-3 py-2.5">PO</th><th className="px-3 py-2.5">Ngày</th><th className="px-3 py-2.5">Mã / quy cách</th><th className="px-3 py-2.5 text-right">Đặt cây</th><th className="px-3 py-2.5 text-right">Nhận cây</th><th className="px-3 py-2.5 text-right">Còn cây</th><th className="px-3 py-2.5 text-right">Còn mét</th><th className="px-3 py-2.5 text-right">Còn kg barem</th><th className="px-3 py-2.5">Trạng thái</th></tr></thead><tbody>{rows.map((row) => <tr key={`${text(row.purchase_order)}:${text(row.purchase_order_row)}`} className="border-t"><td className="px-3 py-2.5"><OpenDoc doctype="Purchase Order" name={text(row.purchase_order)} onOpen={onOpen} /></td><td className="px-3 py-2.5">{date(row.transaction_date)}</td><td className="px-3 py-2.5 font-medium">{text(row.material)}</td><td className="px-3 py-2.5 text-right">{fmt.number(num(row.ordered_bars))}</td><td className="px-3 py-2.5 text-right">{fmt.number(num(row.received_bars))}</td><td className="px-3 py-2.5 text-right font-semibold">{fmt.number(num(row.remaining_bars))}</td><td className="px-3 py-2.5 text-right font-semibold">{fmt.number(num(row.remaining_meters))}</td><td className="px-3 py-2.5 text-right font-semibold">{fmt.number(num(row.remaining_barem_weight_kg))}</td><td className={`px-3 py-2.5 font-medium ${statusClass(row.status)}`}>{text(row.status)}</td></tr>)}</tbody></table></div>;
}

export function DeliveryReceiptTable({ rows, onOpen }: { rows: Row[]; onOpen?: ActionScreenProps["onOpen"] }) {
  const { fmt } = useMetaForge(); const money = (value: number) => fmt.currency ? fmt.currency(value) : fmt.number(value); if (!rows.length) return <Empty>Chưa có phiếu nhập đã ghi sổ.</Empty>;
  return <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[1220px] text-sm"><thead className="bg-muted/50 text-left text-xs text-muted-foreground"><tr><th className="px-3 py-2.5">Phiếu nhập</th><th className="px-3 py-2.5">Ngày nhận</th><th className="px-3 py-2.5">Phiếu giao</th><th className="px-3 py-2.5 text-right">Cây</th><th className="px-3 py-2.5 text-right">Mét</th><th className="px-3 py-2.5 text-right">Kg barem</th><th className="px-3 py-2.5 text-right">Kg thực</th><th className="px-3 py-2.5 text-right">Lệch cân</th><th className="px-3 py-2.5 text-right">Giá trị</th><th className="px-3 py-2.5">PO</th></tr></thead><tbody>{rows.map((row) => <tr key={text(row.purchase_receipt)} className="border-t"><td className="px-3 py-2.5"><OpenDoc doctype="Purchase Receipt" name={text(row.purchase_receipt)} onOpen={onOpen} /></td><td className="px-3 py-2.5">{datetime(row.posting_at)}</td><td className="px-3 py-2.5">{text(row.supplier_invoice_no) || "—"}</td><td className="px-3 py-2.5 text-right">{fmt.number(num(row.qty_bar))}</td><td className="px-3 py-2.5 text-right">{fmt.number(num(row.total_length_m))}</td><td className="px-3 py-2.5 text-right">{fmt.number(num(row.barem_weight_kg))}</td><td className="px-3 py-2.5 text-right">{fmt.number(num(row.actual_weight_kg))}</td><td className="px-3 py-2.5 text-right">{num(row.weight_variance_kg) > 0 ? "+" : ""}{fmt.number(num(row.weight_variance_kg))} kg {row.weight_variance_pct == null ? "" : `(${num(row.weight_variance_pct) > 0 ? "+" : ""}${fmt.number(num(row.weight_variance_pct))}%)`}</td><td className="px-3 py-2.5 text-right">{money(num(row.value))}</td><td className="px-3 py-2.5">{Array.isArray(row.purchase_orders) ? row.purchase_orders.join(", ") : "—"}</td></tr>)}</tbody></table></div>;
}

export function DeliveryPriceTable({ rows, onOpen }: { rows: Row[]; onOpen?: ActionScreenProps["onOpen"] }) {
  const { fmt } = useMetaForge(); const money = (value: number) => fmt.currency ? fmt.currency(value) : fmt.number(value); if (!rows.length) return <Empty>Chưa có lịch sử giá mua.</Empty>;
  return <div className="overflow-x-auto rounded-xl border"><table className="w-full min-w-[920px] text-sm"><thead className="bg-muted/50 text-left text-xs text-muted-foreground"><tr><th className="px-3 py-2.5">Ngày</th><th className="px-3 py-2.5">Quy cách</th><th className="px-3 py-2.5">PO</th><th className="px-3 py-2.5 text-right">Giá/kg</th><th className="px-3 py-2.5 text-right">Giá trước</th><th className="px-3 py-2.5 text-right">Biến động</th><th className="px-3 py-2.5 text-right">Cây</th><th className="px-3 py-2.5 text-right">Kg barem</th></tr></thead><tbody>{rows.map((row, index) => <tr key={`${text(row.purchase_order)}-${index}`} className="border-t"><td className="px-3 py-2.5">{date(row.transaction_date)}</td><td className="px-3 py-2.5 font-medium">{text(row.material)}</td><td className="px-3 py-2.5"><OpenDoc doctype="Purchase Order" name={text(row.purchase_order)} onOpen={onOpen} /></td><td className="px-3 py-2.5 text-right">{money(num(row.rate))}</td><td className="px-3 py-2.5 text-right">{row.previous_rate == null ? "—" : money(num(row.previous_rate))}</td><td className={`px-3 py-2.5 text-right font-medium ${num(row.change_pct) > 0 ? "text-destructive" : num(row.change_pct) < 0 ? "text-emerald-700 dark:text-emerald-400" : ""}`}>{row.change_pct == null ? "—" : `${num(row.change_pct) > 0 ? "+" : ""}${fmt.number(num(row.change_pct))}%`}</td><td className="px-3 py-2.5 text-right">{fmt.number(num(row.qty_bar))}</td><td className="px-3 py-2.5 text-right">{fmt.number(num(row.theoretical_kg))}</td></tr>)}</tbody></table></div>;
}
