/**
 * Danh bạ icon TĨNH.
 *
 * Vì sao không `import * as LucideIcons from "lucide-react"` nữa: cách đó tra được MỌI tên icon,
 * nhưng đổi lại trình đóng gói không thể rung bỏ cây (tree-shake) — nó phải nhét cả ~1500 icon vào
 * bundle. Đo thật trên app Kho: 777 KB thô / 135 KB sau gzip, chỉ để hiển thị 36 cái icon.
 *
 * Với thủ kho cầm điện thoại sóng yếu giữa kho, 135 KB đó là vài giây nhìn màn hình trắng. Đổi lấy
 * sự tiện lợi "gõ tên nào cũng ra" của lập trình viên là một cái giá sai.
 *
 * Import CÓ TÊN như dưới đây thì rung bỏ cây chạy đúng: chỉ những icon thật sự liệt kê mới vào
 * bundle. Tên nào không có ở đây sẽ hiện ô trống VÀ ghi cảnh báo ra console (xem icon.ts) — hỏng
 * thì thấy ngay, không mất âm thầm như bản CLI cũ từng bị review bắt lỗi.
 *
 * THÊM ICON MỚI: khai báo thêm một dòng ở đây. Ba giây, và bundle chỉ to thêm ~0.4 KB.
 */
import type { ComponentType } from "react";
import {
  ArrowLeftRight, Award, Badge, BadgeCheck, BadgeDollarSign, BadgePercent, BadgePlus,
  BarChart3, Bookmark, BookmarkX, BookOpen, BookOpenCheck, BookOpenText, Boxes,
  BrainCircuit, BriefcaseBusiness, Calculator, CalendarCheck2, CalendarClock,
  CalendarDays, CalendarOff, CalendarPlus, CalendarRange, Camera,
  ChartNoAxesCombined, CircleDollarSign, CirclePlus, CircleSlash, ClipboardList, Clock,
  Clock3, ClockAlert, ContactRound, Factory, FileChartColumn, FileCheck2, FileOutput,
  FilePenLine, FilePlus, FileQuestion, FileSignature, FileSpreadsheet, FileText,
  FolderClock, FolderTree, Forklift, Gauge, GitBranch, GitCompareArrows, GraduationCap,
  Grid3x3, HandCoins, Handshake, Hash, HeartHandshake, Layers, Layers3, LayoutDashboard,
  LayoutGrid, Library, List, ListChecks, ListFilter, ListTree, Lock, LockKeyhole,
  LockKeyholeOpen, MailCheck, MailQuestion, Map, MapPinCheck, MapPinned, Megaphone,
  MessagesSquare, MoveRight, Network, NotebookTabs, Package, PackageCheck, PackageOpen,
  PackagePlus, PackageSearch, Paintbrush, Palette, Plane, Printer, Receipt, ReceiptText,
  Ruler, ScanBarcode, ScanFace, ScanLine, ScanSearch, Scale, Scissors, ScrollText,
  Settings, ShieldAlert, ShieldCheck, ShieldPlus, ShoppingBag, Smartphone, Sparkles,
  Table2, TableProperties, Tag, Tags, Target, Timer, TimerReset, TrendingUp,
  TriangleAlert, Truck, Undo2, Upload, UserPlus, UserRoundX, UserSearch, Users,
  UsersRound, WalletCards, Warehouse, Waves, Workflow,
  // Hay gặp ở danh mục ứng dụng do SERVER trả về — khai sẵn để đỡ hiện ô trống.
  Building2, Calendar, ChartPie, CheckCheck, ClipboardCheck, Cog, Contact,
  CreditCard, Database, FileBarChart, Folder, Home, Inbox, Landmark,
  Mail, MapPin, Percent, Phone, ShoppingCart, Star, Wallet, Wrench,
} from "lucide-react";

export const ICON_REGISTRY: Record<string, ComponentType> = {
  "arrow-left-right": ArrowLeftRight,
  award: Award,
  badge: Badge,
  "badge-check": BadgeCheck,
  "badge-dollar-sign": BadgeDollarSign,
  "badge-percent": BadgePercent,
  "badge-plus": BadgePlus,
  "bar-chart-3": BarChart3,
  bookmark: Bookmark,
  "bookmark-x": BookmarkX,
  "book-open": BookOpen,
  "book-open-check": BookOpenCheck,
  "book-open-text": BookOpenText,
  boxes: Boxes,
  "brain-circuit": BrainCircuit,
  "briefcase-business": BriefcaseBusiness,
  calculator: Calculator,
  "calendar-check-2": CalendarCheck2,
  "calendar-clock": CalendarClock,
  "calendar-days": CalendarDays,
  "calendar-lock": CalendarClock,
  "calendar-off": CalendarOff,
  "calendar-plus": CalendarPlus,
  "calendar-range": CalendarRange,
  camera: Camera,
  "chart-no-axes-combined": ChartNoAxesCombined,
  "circle-dollar-sign": CircleDollarSign,
  "circle-plus": CirclePlus,
  "circle-slash": CircleSlash,
  "clipboard-list": ClipboardList,
  clock: Clock,
  "clock-3": Clock3,
  "clock-alert": ClockAlert,
  "contact-round": ContactRound,
  factory: Factory,
  "file-chart-column": FileChartColumn,
  "file-check-2": FileCheck2,
  "file-output": FileOutput,
  "file-pen-line": FilePenLine,
  "file-plus": FilePlus,
  "file-question": FileQuestion,
  "file-signature": FileSignature,
  "file-spreadsheet": FileSpreadsheet,
  "file-text": FileText,
  "folder-clock": FolderClock,
  "folder-tree": FolderTree,
  forklift: Forklift,
  gauge: Gauge,
  "git-branch": GitBranch,
  "git-compare-arrows": GitCompareArrows,
  "graduation-cap": GraduationCap,
  "grid-3x3": Grid3x3,
  "hand-coins": HandCoins,
  handshake: Handshake,
  hash: Hash,
  "heart-handshake": HeartHandshake,
  layers: Layers,
  "layers-3": Layers3,
  "layout-dashboard": LayoutDashboard,
  "layout-grid": LayoutGrid,
  library: Library,
  list: List,
  "list-checks": ListChecks,
  "list-filter": ListFilter,
  "list-tree": ListTree,
  lock: Lock,
  "lock-keyhole": LockKeyhole,
  "lock-keyhole-open": LockKeyholeOpen,
  "mail-check": MailCheck,
  "mail-question": MailQuestion,
  map: Map,
  "map-pin-check": MapPinCheck,
  "map-pinned": MapPinned,
  megaphone: Megaphone,
  "messages-square": MessagesSquare,
  "move-right": MoveRight,
  network: Network,
  "notebook-tabs": NotebookTabs,
  package: Package,
  "package-check": PackageCheck,
  "package-open": PackageOpen,
  "package-plus": PackagePlus,
  "package-search": PackageSearch,
  paintbrush: Paintbrush,
  palette: Palette,
  plane: Plane,
  printer: Printer,
  receipt: Receipt,
  "receipt-text": ReceiptText,
  ruler: Ruler,
  "scan-barcode": ScanBarcode,
  "scan-face": ScanFace,
  "scan-line": ScanLine,
  "scan-search": ScanSearch,
  scale: Scale,
  scissors: Scissors,
  "scroll-text": ScrollText,
  "table-2": Table2,
  settings: Settings,
  "shield-alert": ShieldAlert,
  "shield-check": ShieldCheck,
  "shield-plus": ShieldPlus,
  "shopping-bag": ShoppingBag,
  smartphone: Smartphone,
  sparkles: Sparkles,
  "table-properties": TableProperties,
  tag: Tag,
  tags: Tags,
  target: Target,
  timer: Timer,
  "timer-reset": TimerReset,
  "trending-up": TrendingUp,
  "triangle-alert": TriangleAlert,
  truck: Truck,
  "undo-2": Undo2,
  upload: Upload,
  "user-plus": UserPlus,
  "user-round-x": UserRoundX,
  "user-search": UserSearch,
  users: Users,
  "users-round": UsersRound,
  "wallet-cards": WalletCards,
  warehouse: Warehouse,
  waves: Waves,
  workflow: Workflow,

  "building-2": Building2,
  calendar: Calendar,
  "chart-pie": ChartPie,
  "check-check": CheckCheck,
  "clipboard-check": ClipboardCheck,
  cog: Cog,
  contact: Contact,
  "credit-card": CreditCard,
  database: Database,
  "file-bar-chart": FileBarChart,
  folder: Folder,
  home: Home,
  inbox: Inbox,
  landmark: Landmark,
  mail: Mail,
  "map-pin": MapPin,
  percent: Percent,
  phone: Phone,
  "shopping-cart": ShoppingCart,
  star: Star,
  wallet: Wallet,
  wrench: Wrench,
};
