/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/query-worker/wrangler.jsonc --include-runtime=false --env-interface=QueryWorkerBindings apps/query-worker/worker-configuration.d.ts` (hash: 05dfcf4312c24fdcd802436723ba576d)
interface __BaseEnv_QueryWorkerBindings {
	DB: D1Database;
	REPORT_QUEUE: Queue;
	TENANT_ID: "demo";
	AUTH_MODE: "production";
	JWT_ISSUER: "cloudforge-platform";
	JWT_AUDIENCE: "cloudforge-api";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_QueryWorkerBindings {}
}
interface QueryWorkerBindings extends __BaseEnv_QueryWorkerBindings {}
