/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/gateway-worker/wrangler.jsonc --include-runtime=false --env-interface=GatewayWorkerBindings apps/gateway-worker/worker-configuration.d.ts` (hash: 71b45bcd15e39880a6114567fed7a4a3)
interface __BaseEnv_GatewayWorkerBindings {
	ROUTES: KVNamespace;
	DISPATCHER: DispatchNamespace;
	ASSETS: Fetcher;
	PLATFORM_SUFFIX: "example.com";
	AUTH_MODE: "production";
	INTERNAL_AUTH_KEY_ID: "k1";
	JWT_ISSUER: "cloudforge-platform";
	JWT_AUDIENCE: "cloudforge-api";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_GatewayWorkerBindings {}
}
interface GatewayWorkerBindings extends __BaseEnv_GatewayWorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PLATFORM_SUFFIX" | "AUTH_MODE" | "INTERNAL_AUTH_KEY_ID" | "JWT_ISSUER" | "JWT_AUDIENCE">> {}
}
