/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/tenant-worker/wrangler.jsonc --include-runtime=false --env-interface=TenantWorkerBindings apps/tenant-worker/worker-configuration.d.ts` (hash: 500bfe001d8675caeb2459e5183c5453)
interface __BaseEnv_TenantWorkerBindings {
	FILES: R2Bucket;
	DB: D1Database;
	OUTBOX_QUEUE: Queue;
	TENANT_ID: "demo";
	AUTH_MODE: "production";
	AGGREGATES: DurableObjectNamespace<import("./src/index").AggregateCoordinator>;
	SOCIAL_INGRESS: Fetcher /* cloudforge-social-ingress */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "AggregateCoordinator";
	}
	interface Env extends __BaseEnv_TenantWorkerBindings {}
}
interface TenantWorkerBindings extends __BaseEnv_TenantWorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TENANT_ID" | "AUTH_MODE">> {}
}
