/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=apps/tenant-worker/wrangler.jsonc --include-runtime=false --env-interface=TenantWorkerBindings apps/tenant-worker/worker-configuration.d.ts` (hash: a4445ee594d91dff2cdf2a9b1ec6b1b4)
interface __BaseEnv_TenantWorkerBindings {
	DB: D1Database;
	OUTBOX_QUEUE: Queue;
	TENANT_ID: "demo";
	AUTH_MODE: "production";
	INTERNAL_AUTH_SECRET: string;
	INTERNAL_SERVICE_TOKEN: string;
	SESSION_SECRET: string;
	AGGREGATES: DurableObjectNamespace<import("./src/index").AggregateCoordinator>;
	SOCIAL_INGRESS: Fetcher /* cloudforge-social-ingress */;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "AggregateCoordinator";
	}
	interface Env extends __BaseEnv_TenantWorkerBindings {}
}
interface TenantWorkerBindings extends __BaseEnv_TenantWorkerBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "TENANT_ID" | "AUTH_MODE" | "INTERNAL_AUTH_SECRET" | "INTERNAL_SERVICE_TOKEN" | "SESSION_SECRET">> {}
}
